Ordering-Inc/Ordering-UI-Admin

index.html, package-lock.json, src/components/Header/index.js, src/components/Header/styles.js
STORY: https://app.asana.com/0/1180231464319923/1200280395559669/f
DEMO: https://d.pr/i/bPZKp5
=> Add send feedback btn

src/components/OrderDetails/index.js
STORY: https://app.asana.com/0/1199511033583011/1200280395559683
=> [Fix] crash error in message section

src/components/OrderStatusTypeSelector/index.js
STORY: https://app.asana.com/0/1200268830728150/1200291116723679
=> fix status change error

src/components/Messages/index.js
=> [FIX] messages discrepancies

src/components/OrderDetails/index.js, src/components/OrderDetails/styles.js
https://app.asana.com/0/0/1200286893553005/f
=> Style improvements

src/components/OrderDetails/index.js, src/components/OrderDetails/styles.js
Reverts Ordering-Inc/Ordering-UI-Admin#27
=> Revert "Notification bell when unread"

package-lock.json, src/components/DriverSelector/index.js, src/components/FilterGroupList/index.js, src/components/FilterGroupList/styles.js, src/styles/Select/index.js, src/styles/Selects/index.js
Story: https://app.asana.com/0/1198717964402573/1200343757655711
=> Improvements

src/themes/two/index.js
=> Test branch

package-lock.json, src/themes/two/src/components/BusinessBrandForm/index.js, src/themes/two/src/components/BusinessBrandForm/styles.js, src/themes/two/src/components/BusinessBrands/index.js, src/themes/two/src/components/BusinessBrands/styles.js, src/themes/two/src/components/BusinessInfoSettingList/index.js, src/themes/two/src/components/BusinessInformation/index.js
Story: https://app.asana.com/0/1200268243113852/1200089086311433
=> Update: franchises brand

src/components/Home/index.js
Story: https://app.asana.com/0/inbox/1200268243109536/1201002168055905/1201003493588945
=> Update: contact us link update

package-lock.json, package.json, src/components/AnalyticsCalendar/index.js, src/components/AnalyticsCalendar/styles.js, src/components/BusinessAnalytics/styles.js, src/components/BusinessPromotionGeneralForm/index.js, src/components/DriverAnalytics/styles.js, src/components/OrdersDashboardControls/styles.js, src/components/ProductExtras/index.js, src/components/SettingsDetail/styles.js, src/components/SettingsList/index.js, src/components/SettingsList/styles.js, src/components/SettingsSelectUI/index.js, src/components/SettingsSelectUI/styles.js, src/themes/origin/src/components/MobileSidebarMenu/index.js
Story: https://app.asana.com/0/1200268243113852/1201031267973372
=> Analytics calendar

package-lock.json, src/components/BusinessSchedule/index.js, src/components/BusinessScheduleCopyTimes/index.js, src/components/BusinessScheduleCopyTimes/styles.js, src/components/InvoiceOrdertype/index.js, src/components/InvoiceOrdertype/styles.js, src/components/ProductExtraOptionDetails/index.js, src/components/ProductExtraSubOptionMetaFields/index.js, src/components/ProductExtraSubOptionMetaFields/styles.js
STORY: https://app.asana.com/0/1198717964402573/1201324402930616
=> [FIX] Feedback

package-lock.json, package.json, src/components/BusinessesSelector/index.js, src/components/DriverSelector/index.js, src/components/NotFoundSource/styles.js, src/components/OrderContactInformation/index.js, src/components/OrdersContentHeader/index.js, src/components/OrdersDashboardControls/index.js, src/components/OrdersFilterGroup/index.js, src/components/OrdersManager/index.js, src/components/OrdersTable/index.js, src/components/ProductItemAccordion/index.js
STORY: https://app.asana.com/0/1198717964402573/1201363149239991
=> Improve for driver manager

package-lock.json, package.json, src/components/BusinessList/index.js, src/components/BusinessMenuBasicOptions/index.js, src/components/BusinessMenuBasicOptions/styles.js, src/components/CategoryTreeNode/index.js, src/components/CategoryTreeNode/styles.js, src/components/SingleBusiness/index.js
STORY: https://app.asana.com/0/1198717964402573/1201367565790371
=> Update business menus for sub categories

package-lock.json, src/components/DriversCompanyDetailsForm/index.js, src/components/UserFormDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1201385175496405
=> Update: driver update

src/index.js
Story: https://app.asana.com/0/0/1201391552773830/f
=> [ADD] imports

src/index.js
Story: https://app.asana.com/0/0/1201391552773830/f
=> Add imports

src/components/ReportsDriverOrder/index.js, src/components/ReportsDriverSchedule/index.js, src/components/ReportsDriverSpend/index.js
Story: https://app.asana.com/0/1200268243113852/1201401718769329
=> Reports feedback

package-lock.json, src/components/DriversGroupLogs/index.js
STORY: https://app.asana.com/0/1198717964402573/1201447337099684
=> [Fix] driver group logs

package-lock.json, package.json, src/components/DeliveriesLocation/index.js, src/components/DriverMapMarkerAndInfo/index.js, src/components/DriversLocation/index.js
STORY: https://app.asana.com/0/1198717964402573/1201456246184929
=> [Fix] tracking driver location

src/components/ReportsBusinessSpend/index.js, src/components/ReportsBusinessSpend/styles.js, src/components/ReportsDriverDistance/index.js
Story: https://app.asana.com/0/1200268243113852/1201477637344678
=> Reports extra feedback

src/components/DriversCompaniesList/styles.js, src/components/DriversCompanyWebhooksDetails/index.js, src/components/DriversGroupsList/styles.js
STORY: https://app.asana.com/0/1198717964402573/1201508619952076
=> [Add] missing field

package-lock.json, src/components/BusinessMenu/index.js, src/components/BusinessMenuBasicOptions/index.js, src/components/BusinessPreorder/index.js, src/components/CategoryTreeNode/index.js
STORY: https://app.asana.com/0/1198717964402573/1201572537544843
https://app.asana.com/0/1198717964402573/1201546748570503
=> [Fix] bugs

package-lock.json, src/components/DeliveriesLocation/index.js, src/components/DriversLocation/index.js
STORY: https://app.asana.com/0/1198717964402573/1201563731278608
=> [Fix]  issue for drivers location

index-template.js, src/components/ReportsOrders/index.js, src/components/ReportsSales/index.js
Story: https://app.asana.com/0/1200268243113852/1201566798162609
=> Reports orders

src/components/EditTaxManager/index.js, src/components/ProductDetailsAdvanced/index.js
https://app.asana.com/0/1191220738645130/1201615453265073
=> [FIX] alertstate for editTaxManager

package-lock.json, package.json, src/components/DragScroll/index.js, src/components/EnterprisePromotionConditions/index.js, src/components/EnterprisePromotionList/styles.js, src/components/EnterprisePromotionRules/index.js
STORY: https://app.asana.com/0/1198717964402573/1201619577538352
=> [FIX] feedback for Advanced offers

src/index.js
Added new import/export components in index
=> [ADD] Report Import/Export

src/components/EnterprisePromotionListing/index.js, src/components/EnterprisePromotionListing/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201681547194313
=> Disable event

src/components/LanguageTransTable/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201627418040245
=> [Fix] Search issue for Language manager

package.json, src/components/DriversGroupBusinesses/index.js, src/components/DriversGroupBusinesses/styles.js, src/components/DriversGroupDetails/index.js, src/components/DriversGroupGeneralForm/index.js, src/components/DriversGroupGeneralForm/styles.js, src/components/DriversGroupPaymethods/index.js, src/components/DriversGroupsList/index.js, src/components/DriversGroupsListing/index.js, src/components/DriversGroupsListing/styles.js, src/components/UserAddForm/index.js, src/components/UsersListing/index.js, src/components/UsersListingHeader/index.js, src/components/UsersListingHeader/styles.js, src/components/WizardDelivery/index.js, src/components/WizardDelivery/styles.js, src/contexts/ThemeContext/index.js, src/utils/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201679058829598
=> [FEAT] Delivery system tutorial

src/components/OrderingProductDetails/index.js, src/components/OrderingProductDetails/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201716013315728
=> [Fix] feedback for storefronts management

src/components/BusinessMenuBasicOptions/index.js, src/components/DriversGroupsListing/index.js, src/components/SideBar/index.js, src/components/SideBar/styles.js, src/components/UserAddForm/index.js, src/components/UsersListing/index.js, src/contexts/ThemeContext/index.js
STORY: https://app.asana.com/0/1198717964402573/1201679058829601
=> [Update] delivery system tutorial

src/components/BusinessProductsCategoyInfo/index.js, src/components/ProductDetatilsInformation/index.js
Story: https://app.asana.com/0/0/1200735055841207/f
=> [FIX] seo feedback

src/components/DeliveriesManager/index.js
Story: https://app.asana.com/0/1200268243113852/1201746843882500
=> Update: delivery dashboard

src/components/UserFormDetails/index.js, src/components/UserFormDetails/styles.js, src/components/UserProfileForm/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1201716272790262
=> Driver restriction

src/components/BusinessReviewDetails/index.js
=> show order id in sidebar review detail

src/components/OrderDetails/index.js, src/components/OrdersListing/index.js, src/components/OrdersManager/index.js, src/components/OrdersTable/index.js, src/components/ProductItemAccordion/index.js, src/components/WizardOrders/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1201674419432973
=> [Update]: Wizard orders feedback

src/components/BusinessProductAddForm/index.js, src/components/UsersList/index.js, src/components/UsersList/styles.js, src/components/WizardDelivery/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201674415314944
=> [Fix] feedback for wizard business

src/components/BusinessProductList/index.js, src/components/BusinessProductList/styles.js, src/components/BusinessSpreadSheet/index.js, src/components/ProductDetatilsInformation/index.js, src/components/ProductDetatilsInformation/styles.js, src/components/ProductSummary/index.js, src/components/ProductSummary/styles.js, src/components/SingleBusinessProduct/index.js
Story:
https://app.asana.com/0/1200550251832819/1201126531558202
Demo:
https://d.pr/v/NMBeW1
https://d.pr/v/0XI3HH
https://d.pr/v/jEP062
=> Product regular price

src/components/Marketing/EnterprisePromotionConditions/index.js, src/components/Marketing/EnterprisePromotionSpecficCategory/index.js, src/components/Marketing/EnterprisePromotionSpecficProducts/index.js, src/components/Marketing/EnterprisePromotionSpecficProducts/styles.js, src/components/Shared/SelectBusinessCategories/index.js, src/components/Shared/SelectBusinessProducts/index.js
ASANA TASK: https://app.asana.com/0/0/1201728766513282/f
Video: https://d.pr/v/7tzwRa
=> Change product-promotion structure and update slug to show products

src/components/Stores/ImporterForm/index.js
=> add parent_category_id field

index-template.js, src/components/Stores/ImporterForm/index.js, template/assets/files/ordering_business_example.csv, webpack.dev.js, webpack.prod.js
=> add example csv link

src/components/Stores/ProductDetailsAdvanced/index.js, src/components/Stores/ProductDetailsAdvanced/styles.js
=> add field for product calories

src/components/Orders/OrderDetails/index.js, src/components/Shared/SideBar/index.js
Story: https://app.asana.com/0/1200268243113852/1201830818412540
=> Update: wizard orders feedback

src/components/Orders/Messages/index.js
Story: https://app.asana.com/0/1199511033583011/1201789056797046/f
Image: https://d.pr/uZV6VN
=> [ADD] messages comment section

src/components/BusinessIntelligence/index.js, src/components/Settings/index.js, src/index.js
Story: https://app.asana.com/0/1199511033583011/1201840507092948/f
=> [FIX] Missing imports

src/components/Shared/Schedule/index.js, src/components/Stores/BusinessProductList/index.js, src/styles/Toast/index.js
STORY: https://app.asana.com/0/1198717964402573/1201674415314944
=> [Update] UI

src/components/Marketing/EnterprisePromotionConditions/index.js, src/components/Marketing/EnterprisePromotionMaxOrders/index.js, src/components/Marketing/EnterprisePromotionMaxOrders/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201837431816400
=> [Feat] orders count condition

src/components/BusinessIntelligence/ReportsDriverOrderTime/index.js
STORY: https://app.asana.com/0/1198717964402573/1201845529323697
=> [Fix] feedback for report

src/components/Shared/ProgressRing/index.js, src/components/Shared/index.js, src/components/Stores/BusinessProductList/index.js, src/components/Stores/ProductDetailsAdvanced/index.js, src/components/Stores/ProductSummary/index.js, src/components/Stores/ProductSummary/styles.js, src/components/Stores/SingleBusinessProduct/index.js
Demo: 
https://d.pr/i/tj5Ffy
https://d.pr/i/pmvSxe
https://d.pr/v/HdNq6c
=> add product cost , change design product details

src/components/Users/CustomersListing/index.js, src/components/Users/UserDetails/index.js, src/components/Users/UserDetails/styles.js, src/components/Users/UserProfileForm/index.js, src/components/Users/UsersListing/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201830703384106
=> [Fix] feedback for Twilio customer login

src/components/Marketing/EnterprisePromotionRules/index.js, src/components/Marketing/EnterprisePromotionRules/styles.js
STORY: https://app.asana.com/0/1198717964402573/1201879140522007
=> [Update] feedback for advanced offers

src/components/Stores/ProductSummary/index.js
=> Cost feedback

src/components/Stores/ProductDetatilsInformation/index.js, src/components/Stores/ProductDetatilsInformation/styles.js
=> Regular price feedback

src/components/Loyalty/PointsWalletBusinessDetail/index.js, src/components/Loyalty/PointsWalletLevels/index.js, src/components/SidebarMenu/index.js, template/config.json, yarn.lock
=> Loyalty feedback

src/components/Orders/DriverSelector/index.js, src/components/Orders/Messages/index.js, src/components/Orders/OrderDetails/index.js, src/components/Orders/OrdersListing/index.js, src/components/Orders/OrdersManager/index.js, src/styles/MultiSelect/index.js, src/styles/Select/index.js
=> Wizard orders

src/components/Stores/ProductDetailsAdvanced/index.js
remove unused price per product weight unit.
=> product weight feedback

src/components/Stores/ProductDetatilsInformation/index.js
=> not allow that price same with price

src/components/Orders/WizardOrders/index.js
Story: https://app.asana.com/0/0/1201922344424126/f
=> [FIX] avoid slash in text

src/components/Users/CustomerPointsWallet/index.js
Story: https://app.asana.com/0/1200268243113852/1201928710587901
=> Update: points wallet

src/components/Delivery/DriversGroupOrders/index.js
Story: https://app.asana.com/0/1201859974879441/1201929011779486/f
=> [FIX] language variable

src/components/Orders/OrderBill/index.js, src/components/Orders/OrderBill/styles.js, src/components/Orders/OrderDetailsHeader/index.js, src/components/Users/CustomerCashWalletEvents/index.js, src/components/Users/CustomerCashWalletEvents/styles.js, yarn.lock
STORY: 
https://app.asana.com/0/1198717964402573/1201937716602509
https://app.asana.com/0/1198717964402573/1201937716602508
https://app.asana.com/0/1198717964402573/1201937716602507
=> [Update] feedback for cash wallet

src/components/Orders/Messages/styles.js, src/components/Orders/OrderDetails/styles.js, src/components/Stores/BusinessPaymentMethods/index.js, src/components/Users/CustomerDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1201935700127535
=> Dashboard update

src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/ProductExtraOptionDetails/styles.js, src/components/Stores/ProductExtras/index.js, src/components/Stores/ProductExtras/styles.js, src/components/Stores/ProductSummary/index.js
Story: https://app.asana.com/0/1200268243113852/1201893864502836
=> Products update

src/components/Delivery/DeliveryUsersListing/index.js, src/components/Delivery/UserDetails/index.js, src/components/Delivery/UserDetails/styles.js, src/components/Delivery/UserDetailsMenu/index.js, src/components/Delivery/UsersList/index.js, src/components/Delivery/UsersList/styles.js
story: https://app.asana.com/0/1200268243113852/1201893864502843
=> Update: drivers section

src/components/SidebarMenu/index.js
STORY: https://app.asana.com/0/1198717964402573/1201931136690854
=> [Fix] feedback for business owner

src/components/Stores/SingleBusinessSubCateogries/index.js, src/components/Stores/SingleBusinessSubCateogries/styles.js
STORY: https://app.asana.com/0/1198717964402573/1201894042190283
=> [Update] categories rank

src/components/Stores/BusinessBrandListing/index.js
STORY: https://app.asana.com/0/1198717964402573/1201957658179738
=> [Fix] feedback for brands

src/components/Orders/Messages/index.js
Story: https://app.asana.com/0/1200268243113852/1201966846338306
=> Update: message focus

src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/ProductIngredientDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1201965988098202
=> Update: products

src/components/Users/CustomerCashWalletEvents/index.js
STORY: https://app.asana.com/0/1198717964402573/1201937716602510
=> [Update] add order number

src/components/Stores/ProductDetails/index.js, src/components/Stores/ProductGallery/index.js, src/components/Stores/ProductSummary/index.js, src/components/Stores/ProductVideos/index.js, src/components/Stores/ProductVideos/styles.js
=> add product gallery video

src/components/Settings/CityDetails/index.js, src/components/Settings/PlaceListing/index.js
Story: https://app.asana.com/0/0/1201896440615457/f
Video: https://d.pr/v/1t9J8l
=> hide city admin

src/components/Stores/ProductExtraOptions/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201990987736148
=> [Fix] input issue

src/components/Stores/BusinessProductsCategoyInfo/index.js, src/components/Stores/BusinessProductsCategoyInfo/styles.js, src/components/Stores/SeoOptions/index.js, template/config.json
Story: https://app.asana.com/0/1200268243113852/1201126723019012
=> Short long description

src/components/BusinessIntelligence/ReportsDriverFilter/index.js, src/components/SidebarMenu/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202045819607959
=> [Update]: reportsFilter

src/components/Marketing/EnterprisePromotionRules/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202050799813737
=> [Add] max validation

src/components/Marketing/EnterprisePromotionDetails/index.js
Story; https://app.asana.com/0/1191220738645130/1202050799813740
demo; https://d.pr/v/HgXdZI
=> [ADD] save promotions details when change tabs

src/components/BusinessIntelligence/AnalyticsOrdersStatus/index.js, src/components/BusinessIntelligence/InvoiceBusinessPdf/index.js, src/components/Orders/Messages/index.js, src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderLogisticInformation/index.js, src/components/Orders/OrderStatusSubFilter/index.js, src/components/Orders/OrderStatusTypeSelector/index.js, src/components/Orders/OrdersCards/index.js, src/components/Orders/OrdersTable/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202064907416153
=> [Add] new order statuses

src/components/Stores/BusinessDeliveryZoneList/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202095057201695
=> [Fix] add delivery zone

src/components/Shared/Modal/styles.js
STORY: https://app.asana.com/0/1198717964402573/1201984915377856
=> [Fix] iOS issue

src/components/Settings/Settings/index.js, src/components/Settings/SettingsDetail/index.js, src/components/Settings/SettingsDetail/styles.js, src/components/Settings/SettingsList/index.js
Story: https://app.asana.com/0/1200268243113852/1202094174200721
=> Update: max preorder day

src/components/BusinessIntelligence/AnalyticsCustomerSatisfaction/index.js, src/components/BusinessIntelligence/AnalyticsOrdersOrSales/index.js, src/components/BusinessIntelligence/AnalyticsOrdersStatus/index.js, src/components/BusinessIntelligence/AnalyticsProductCategories/index.js, src/components/BusinessIntelligence/AnalyticsRegisterUsers/index.js, src/components/SidebarMenu/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202013353877503
=> [Fix] Feedback iPad

src/components/Delivery/DeliveryUsersListing/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202089052399193
=> [Update]: Driver feedback

src/components/Marketing/EnterprisePromotionDetails/index.js, src/components/Marketing/EnterprisePromotionList/index.js, src/components/Marketing/EnterprisePromotionRules/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202050799813735
=> [Fix] Promotions feedback

src/components/Marketing/CampaignDetailGeneral/index.js, src/components/Marketing/CampaignSignUpOption/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202108961829503
=> Sales marketing feedback

src/components/Orders/OrderDashboardSLASetting/index.js
Story:  https://app.asana.com/0/1200550251832819/1202119741582160
Demo:  https://d.pr/v/ulEAEL
=> remove time limit and last Timer

src/components/Settings/SettingsSelectUI/index.js, src/components/Settings/SettingsSelectUI/styles.js, src/styles/Select/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202076503225666
=> [Add] custom option

src/components/SidebarMenu/index.js, src/components/Stores/BusinessProductsListing/index.js, src/components/Stores/BusinessProductsListing/styles.js, src/components/Stores/BusinessSummary/index.js, template/app.js, template/components/ListenPageChanges/index.js, template/pages/BusinessProductsList/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201936820213213
=> [Add] products section

src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/ProductExtraOptions/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201990987736152
=> [Update] option update

src/components/Stores/SingleBusinessSubCateogries/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202087854085716
=> [Update] subcategory rank

src/components/Marketing/EnterprisePromotionRules/index.js, src/components/Marketing/EnterprisePromotionRules/styles.js
story: https://app.asana.com/0/1191220738645130/12021446603
22243
=> [ADD] public and automatic offer checkbox

src/components/Stores/BusinessPromotionGeneralForm/index.js, src/components/Stores/BusinessPromotionGeneralForm/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202125469298144
=> [Add] fields for advanced offer active

src/components/Stores/ProductVideos/index.js
add validation for display thumbnail image and correct video gallery in product form.
bug story:  https://app.asana.com/0/1200550251832819/1202075802560497
=> add validation of youtube video Id

src/components/Stores/BusinessPaymentMethods/index.js, src/components/Stores/BusinessPaymentMethods/styles.js, src/components/Stores/BusinessWalletsList/index.js, src/components/Stores/BusinessWalletsList/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202051951332932
=> [Feat] business wallet setting

src/components/Shared/SpreadSheetEditor/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202157647805182
=> [Fix] spreadsheet edit clickable bug

src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/ProductExtraOptionDetails/styles.js, src/components/Stores/ProductExtraOptionForm/index.js, src/components/Stores/ProductExtraOptionForm/styles.js, src/components/Stores/ProductExtraOptions/index.js
STORY: https://app.asana.com/0/1198717964402573/1201990987736152
=> [Fix] extra option validation

src/components/Stores/BusinessProductsListing/index.js, src/components/Stores/BusinessProductsListing/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202141091343500
=> [Update] disabled category section

src/components/Downloads/PurchasedProductsList/index.js, src/components/Downloads/PurchasedProductsList/styles.js, src/components/downloads/FreeProductsList/index.js, src/components/downloads/FreeProductsList/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202155728098672
=> [Fix] Downloads Feedback

src/components/Orders/OrderBill/index.js, src/components/Orders/OrdersTable/index.js, src/components/SidebarMenu/index.js
STORY: https://app.asana.com/0/1198717964402573/1202143272105040
=> [Update] driver manager

src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderDetails/styles.js
https://app.asana.com/0/1191220738645130/1202142495686646
=> [ADD] place spot for order details

src/components/Marketing/EnterprisePromotionList/index.js, src/components/Marketing/EnterprisePromotionList/styles.js, src/components/Orders/OrdersContentHeader/index.js
STORY: https://app.asana.com/0/1198717964402573/1202155312118177
=> [Fix] iPhone feedback

src/components/Marketing/CampaignDetailGeneral/index.js, src/components/Marketing/CampaignDetailGeneral/styles.js, template/helmetdata.json, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202163855981193
=> update: sales and marketing

src/components/Stores/BusinessDeliveryZoneDetails/index.js, src/components/Stores/BusinessDeliveryZoneInformation/index.js, src/components/Stores/BusinessDeliveryZoneList/index.js, yarn.lock
STORY: https://app.asana.com/0/inbox/1198717964396322/1202120875514745/1202117293896062
=> [Update] add delivery zone

src/components/Stores/BusinessMenuCategoryTreeNode/index.js
STORY: https://app.asana.com/0/1198717964402573/1202169472482906
=> [Fix] menu category select

src/components/Marketing/EnterprisePromotionDetails/index.js, src/components/Marketing/EnterprisePromotionMaxOrders/index.js, src/components/Marketing/EnterprisePromotionSpecficCategory/index.js, src/components/Marketing/EnterprisePromotionSpecficProducts/index.js
https://app.asana.com/0/1191220738645130/1202190614377517
=> [Fix] advanced offers feedback internal release

src/components/Marketing/CampaignDetailGeneral/index.js, src/components/Marketing/CampaignDetailGeneral/styles.js, src/components/Marketing/CampaignHeader/index.js, src/components/Marketing/CampaignHeader/styles.js, src/components/Marketing/CampaignSignUpOption/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202183333069167
=> Campaign feedback

src/components/Stores/ProductDetailsAdvanced/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202175772465611
Demo:  https://d.pr/v/U1fCFS ,   https://d.pr/v/G05Yn9
=> bug insert maximum quantity is null

src/components/Stores/BusinessProductList/index.js, src/components/Stores/BusinessProductsListing/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202100889553743
=> [Fix] business products for lazy load recommended

src/components/Stores/BusinessPaymentMethods/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202183333069166
=> [Update] hide wallets for disabled setting

src/components/Stores/index.js, src/index.js
Story: https://app.asana.com/0/1201324366625225/1202202232842218/f
=> [ADD] missing imports store components

src/components/Delivery/DriversGroupGeneralForm/styles.js, src/components/Delivery/UserAddForm/styles.js, src/components/Loyalty/PointsWalletBusinessDetail/styles.js, src/components/Loyalty/PointsWalletBusinessList/styles.js, src/components/Settings/LanguageSetting/styles.js, src/components/Settings/SettingsDetail/styles.js, src/components/Stores/ProductDetatilsInformation/styles.js, src/components/Users/UserAddForm/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202164307923413
=> [Fix] iPad feedback

package.json, src/components/Shared/ColumnAllowSettingPopover/index.js, src/styles/Select/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202203059399562
=> [Fix] popper issue

src/components/Login/LoginForm/index.js, src/components/Login/LoginForm/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202134957663286
=> [Add] ReCaptcha functionality

src/components/Marketing/CampaignDetailGeneral/index.js, src/components/Marketing/CampaignEmail/index.js, src/components/Marketing/CampaignNotification/index.js, src/components/Marketing/CampaignPopup/index.js, src/components/Marketing/CampaignSMS/index.js, src/components/Marketing/CampaignWebHook/index.js, src/components/Marketing/CampaignWhatsapp/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202203059399579
=> Update: campaign feedback

package.json, src/components/Orders/OrderContactInformation/styles.js, src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderDetailsHeader/index.js, src/components/Orders/OrderToPrint/index.js, src/components/Orders/OrderToPrint/styles.js, src/components/Orders/ProductItemAccordion/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202097372453261
=> [Feat] Order to Print

src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderContactInformation/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202143272105042
=> [Update] Driver selector

src/components/Stores/BusinessProductsListing/index.js, src/components/Stores/BusinessProductsListing/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202205054545847
=> [Update] products page

src/components/Orders/OrderDetailsHeader/index.js, src/components/Orders/OrderDetailsHeader/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202183674834021
=> [Add] Stripe link

src/components/CartRecovery/RecoveryNotificationList/index.js, src/components/CartRecovery/SingleRecoveryNotification/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202213633765305
=> Update: recovery action feedback

src/components/Orders/OrderBill/index.js, src/components/Orders/OrderBill/styles.js, src/components/Orders/OrderDetails/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202183674834024
=> [Add] order refund button

package.json, src/components/Delivery/UserAddForm/index.js, src/components/Delivery/UserProfileForm/index.js, src/components/Marketing/EnterprisePromotionGeneralDetails/index.js, src/components/Shared/ImageCrop/index.js, src/components/Shared/ImageCrop/styles.js, src/components/Shared/index.js, src/components/Stores/AddBusinessForm/index.js, src/components/Stores/BusinessBrandGENDetail/index.js, src/components/Stores/BusinessInformation/index.js, src/components/Stores/BusinessProductAddForm/index.js, src/components/Stores/BusinessProductsCategoyInfo/index.js, src/components/Stores/BusinessTypeDetail/index.js, src/components/Stores/ProductDetatilsInformation/index.js, src/components/Stores/ProductTagDetails/index.js, src/components/Users/UserAddForm/index.js, src/components/Users/UserProfileForm/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202155736009760
=> [Feat]: Add image crop

src/components/Stores/ProductVideos/index.js
STORY: https://app.asana.com/0/home/1200550251832815/1201868446413004
DEMO: https://d.pr/v/4pV3YA
=> add validation for product gallery

src/components/Orders/OrderDetailsHeader/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202232978285348
=> [Add] pay data for wallet events

src/components/Shared/ImageCrop/index.js, src/components/Shared/Modal/index.js, src/components/Stores/BusinessProductsCategoyDetails/index.js, src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/ProductExtraOptions/index.js, src/components/Stores/ProductExtraSuboption/index.js, src/components/Stores/ProductGallery/index.js, src/components/Stores/SeoOptions/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202237164968349
=> Update: image crop

src/components/Downloads/PurchasedProductsList/index.js, src/components/downloads/FreeProductsList/index.js
STORY: https://app.asana.com/0/1198717964402573/1202255648722140
=> [Update] App link

src/components/Stores/BusinessProductsCategoyInfo/index.js
Story: https://app.asana.com/0/1200268243113852/1202254152817187
=> Update: duplicated description

src/components/Settings/SettingsList/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202254753959593
Demo: https://d.pr/v/5em1Lj
=> add validation for Platform Fee settings

src/components/Orders/OrderDashboardSLASetting/index.js, src/components/Orders/OrdersCards/index.js, src/components/Orders/OrdersContentHeader/index.js, src/components/Orders/OrdersTable/index.js, yarn.lock
Story: https://app.asana.com/0/home/1200550251832815/1202269914718486
Demo: https://d.pr/v/8OzHd7, https://d.pr/v/NXy4ID, https://d.pr/v/chS6RA
=> Order deadline delayed

src/components/Stores/index.js, src/index.js
Story: https://app.asana.com/0/1201324366625225/1202202232842218/f
=> [FEAT] Store imports missing

src/components/Stores/index.js, src/index.js
Story: https://app.asana.com/0/1201324366625225/1202202232842218/f
=> fix imports

src/components/Stores/ProductExtras/index.js, src/components/Stores/ProductExtras/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202275055102788
=> [Add] allow product extra rank to drag

src/components/Marketing/EnterprisePromotionDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1202260802722717
=> [Fix] duplicate offer issue

src/components/Loyalty/PointsWallet/index.js, src/components/Loyalty/PointsWalletBusinessList/index.js
STORY: https://app.asana.com/0/1198717964402573/1202302616155296
=> [Fix] weird behavior

src/components/Shared/SelectBusinessProducts/index.js
STORY: https://app.asana.com/0/1198717964402573/1202302035703781
=> [Add] validate products for offer

src/components/Stores/PaymentOptionSquare/index.js, src/components/Stores/PaymentOptionSquare/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202304077734087
=> [Add] Sandbox field

src/components/Stores/ProductDetailsAdvanced/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202284402664223
Demo: https://d.pr/i/5fGkK0, https://d.pr/v/xOWjFj
=> Dashboard product detail

src/components/Stores/ProductDetatilsInformation/index.js
STORY: https://app.asana.com/0/1198717964402573/1202323298440802
=> [Update]  product quantity field

src/components/Stores/ProductDetatilsInformation/index.js
story: https://app.asana.com/0/1200268243113852/1202210918352348
=> [Update]: Seo keywords

src/components/Downloads/PurchasedProductsList/index.js, src/components/Downloads/PurchasedProductsList/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202330826177691
=> [Update] purchased products links

src/components/Settings/SettingsList/index.js
Demo: https://d.pr/v/RwDjFp
Story: https://app.asana.com/0/home/1200550251832815/1202284745659851
=> fix invaid input

src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/ProductExtraOptionForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1202346553998349
=> [Update] product option detail

src/components/Settings/SettingsList/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202354084930194
Demo:https://d.pr/v/8dBmBJ
=> fix max platform settings issue

src/components/Stores/BusinessDetail/index.js, src/components/Stores/BusinessDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1202342617303810
=> Update: ribbon update

src/components/Users/ProfessionalBusinessService/index.js, src/components/Users/ProfessionalCategoryTreeNode/index.js
Story: https://app.asana.com/0/1200268243113852/1202355578389384
=> Update: professional feedback

src/components/Stores/ProductDetatilsInformation/index.js, src/components/Stores/SeoOptions/index.js
Story: https://app.asana.com/0/1200268243113852/1202364187822837
=> Updtae: seo keywords

src/components/SidebarMenu/index.js, template/app.js
STORY: https://app.asana.com/0/inbox/1198717964396322/1202362736162333/1202368997801903
=> [Update] show downloads for only admin users

src/components/Stores/ProductDetailsAdvanced/index.js
Story: https://app.asana.com/0/home/1200550251832815/1201126531558193
Demo: https://d.pr/v/sptJBd
=> fix settings functionality

index-template.js, src/components/Orders/OrderStatusTypeSelector/index.js
STORY: https://app.asana.com/0/1198717964402573/1202378387833948
=> [update] order status selector

src/components/Settings/Cms/index.js
Story: https://app.asana.com/0/1199511033583011/1202248584307821/f
Video: https://d.pr/v/CKZUfR
=> [FEAT] CMS modal fix

src/components/Orders/OrderStatusTypeSelector/index.js
STORY: https://app.asana.com/0/inbox/1198717964396322/1202389062894839/1202384440004311
=> [Fix] orders status feedback

src/components/Marketing/CampaignAmountOption/index.js, src/components/Marketing/CampaignDetailContent/index.js, src/components/Marketing/CampaignSignUpOption/index.js
Story: https://app.asana.com/0/1200268243113852/1202376893486328
=> Update: marketing feedback

src/components/Marketing/CampaignDetailGeneral/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202405520675525
=> Update: marketing update

src/components/Stores/BusinessInformation/index.js, src/components/Stores/BusinessInformation/styles.js, template/config.json
Story: https://app.asana.com/0/1200268243113852/1202408286159610
=> [Update]: business price filter

src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderDetails/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202184561649925
=> [Add] reject reasons

src/components/Stores/BusinessInformation/index.js
Story: https://app.asana.com/0/inbox/1200268243109536/1202420570837563/1202421103892052
=> [Update]: price filter

src/components/Orders/OrderBill/index.js, src/components/Orders/OrderBill/styles.js
Story: https://app.asana.com/0/1199511033583011/1202354581530808/f
Video: https://d.pr/v/59mrMj
=> [FEAT] Show delivery option

template/components/HelmetTags/index.js, template/config.json, template/helmetdata.json
STORY: https://app.asana.com/0/1198717964402573/1202397715153919
=> [Update] app name

src/components/Login/ForgotPasswordForm/index.js, src/components/Login/ForgotPasswordForm/styles.js
Story: https://app.asana.com/0/1200268243113852/1202295471114432
=> Update: forgot password

src/components/Loyalty/PointsWalletBusinessDetail/index.js, src/components/Users/CustomerPointsWallet/index.js, template/pages/CustomersList/index.js
Story: https://app.asana.com/0/1200268243113852/1202444557328968
=> [Update]: loyalty

src/components/Home/HomePage/index.js, src/components/Home/HomePage/styles.js, template/app.js
Story: https://app.asana.com/0/1200268243113852/1202274439832395
=> [Feat]: Canny integration

src/components/Stores/BusinessDeliveryZoneDetails/index.js, src/components/Stores/BusinessDeliveryZoneInformation/index.js, src/components/Stores/BusinessDeliveryZoneInformation/styles.js
STORY: https://app.asana.com/0/inbox/1198717964396322/1202190954767788/1202462498782765
=> [Add] delivery zone from KML

src/components/Stores/BusinessProductsListing/index.js, template/config.json, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202285052024798
=> [Update] default products importer

src/components/Home/HomePage/index.js, src/components/Home/HomePage/styles.js
Story: https://app.asana.com/0/1200268243113852/1202474108266401
=> Update: canny

src/components/Loyalty/PointsWalletLevels/index.js, src/components/Loyalty/PointsWalletLevels/styles.js, src/components/Loyalty/SingleLoyaltyLevel/styles.js
Story: https://app.asana.com/0/inbox/1200268243109536/1202212986318525/1202353570142423
=> Update: loyalty level

src/components/Loyalty/PointsWalletBusinessDetail/index.js, src/components/Loyalty/PointsWalletBusinessDetail/styles.js
Story: https://app.asana.com/0/1202390334219072/1202212986318525/f
=> Update: loyalty

src/components/Stores/ChildMapplingList/index.js, src/components/Stores/ChildMapplingList/styles.js, src/components/Stores/ImporterForm/index.js, src/components/Stores/ImporterForm/styles.js, src/components/Stores/ImportersListing/index.js
STORY: https://app.asana.com/0/1198717964402573/1202285052024810
=> [Add] multiple importer

src/components/Settings/SettingsList/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202254753959593
Demo: https://d.pr/v/Fv3dsT
=> feedback update invalid input

src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderDetails/styles.js, src/utils/index.js
STORY: https://app.asana.com/0/1198717964402573/1202428717192223
=> [Add] order reject comment tags

src/components/Stores/ChildMapplingList/index.js, src/components/Stores/ImporterForm/index.js, src/components/Stores/ImporterForm/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202483588294513
=> [Fix] Feedback importer

src/index.js
=> [FEAT] Fix import

src/components/Shared/Schedule/index.js, src/components/Shared/Schedule/styles.js
Story: https://app.asana.com/0/1200268243113852/1202482858626299
=> Update: time format

src/components/Orders/Messages/index.js, src/components/Orders/OrderStatusFilterBar/index.js
Story: https://app.asana.com/0/1202390334219072/1202467383905259/f
Demo:  https://d.pr/v/cYOAdU, https://d.pr/i/YZcGBL
=> Different improvement

src/components/Stores/index.js, src/index.js
Story: https://app.asana.com/0/1201324366625225/1202525362017010/f
=> [FEAT] Single Business missing import

src/components/Stores/index.js, src/index.js
Story: https://app.asana.com/0/1201324366625225/1202538493569811/f
=> [FEAT] Missing import

src/components/Settings/SiteSettingDetails/index.js, src/components/Settings/SiteSettingDetails/styles.js, src/components/Settings/SitesAuthSettings/index.js
STORY: https://app.asana.com/0/1198717964402573/1202541072115890
=> [Fix] Error alert

src/components/Orders/OrderStatusFilterBar/index.js, src/components/Orders/OrdersCards/index.js, src/components/Orders/OrdersCards/styles.js, src/components/Orders/OrdersListing/index.js, src/components/Orders/OrdersTable/index.js, src/components/Orders/OrdersTable/styles.js, src/components/Shared/Pagination/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202556242462975
=> [Update] Speed improvement

src/components/Stores/ImporterForm/index.js, src/components/Stores/ImporterJobForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1202560902296984
=> [Update] product options importer

src/components/Orders/DeliveriesManager/index.js, src/components/Orders/DeliveryDashboard/index.js, src/components/Orders/OrderStatusFilterBar/index.js, src/components/Orders/OrderStatusSubFilter/index.js, src/components/Orders/OrdersDashboardList/naked.js, src/components/Orders/OrdersManager/naked.js
Story: https://app.asana.com/0/home/1200550251832815/1202467383905259
Demo: https://d.pr/v/bgoaOv, https://d.pr/v/cN21y8
=> feedback different improvement

src/components/Stores/ImporterHelpContent/index.js, src/components/Stores/ImporterHelpContent/styles.js, src/components/Stores/ImporterJobForm/index.js, src/components/Stores/ImportersListing/index.js, src/components/Stores/ImportersListing/styles.js
Story: https://app.asana.com/0/1200550251832819/1202285052024862
Demo: https://d.pr/v/lqkAE9, https://d.pr/v/T8fIm8
=> Add importer

src/components/Orders/OrderContactInformation/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202570999300075
Demo: https://d.pr/v/3RyYy2
=> add country code in phone

src/components/Orders/OrderDetails/index.js, src/components/Orders/OrdersCards/index.js, src/components/Orders/OrdersTable/index.js
STORY: https://app.asana.com/0/1198717964402573/1202568310796749
=> [Fix] delivery time feedback

src/components/Stores/ImporterHelpContent/index.js, src/components/Stores/ImporterHelpContent/styles.js, src/components/Stores/ImporterJobForm/index.js, src/components/Stores/ImportersListing/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202285052024862
Demo: https://d.pr/v/MX8lZ8
=> update importer content

src/components/Orders/OrderStatusSubFilter/index.js, src/components/Orders/OrdersManager/index.js
Main Story: https://app.asana.com/0/home/1200550251832815/1202467383905259
Story: https://app.asana.com/0/home/1200550251832815/1202637702344593
Demo: https://d.pr/v/H7i9tY
=> remove sub filter count

src/components/Orders/OrdersFilterGroup/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202626745621132
Demo: https://d.pr/v/VZjXDY, https://d.pr/v/lH5iH2
=> feedback filter

src/styles/Selects/index.js
STORY: https://app.asana.com/0/1198717964402573/1202652142051894
=> [Update] mouse hover effect

src/components/Delivery/UserDetails/index.js, src/components/Delivery/UserDetails/styles.js, src/components/Delivery/UserDetailsMenu/index.js
Story: https://app.asana.com/0/1200550251832819/1202465862178685
Demo: https://d.pr/v/5dlleA
=> Driver schedules

package.json, src/components/Orders/Appointments/CalendarHeader.js, src/components/Orders/Appointments/EventComponent.js, src/components/Orders/Appointments/index.js, src/components/Orders/Appointments/styles.js, src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderDetailsHeader/index.js, src/components/Orders/OrderDetailsHeader/styles.js, src/components/Orders/index.js, src/components/SidebarMenu/index.js, src/index.js, template/app.js, template/components/ListenPageChanges/index.js, template/config.json, template/helmetdata.json, template/pages/Appointments/index.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202203375075815
=> [Add] Appointments

src/components/SidebarMenu/index.js, template/app.js
STORY: https://app.asana.com/0/1198717964402573/1202702616686301
=> Hide features for driver managers

src/components/Stores/BusinessInformation/index.js, src/components/Stores/BusinessInformation/styles.js
Story: https://app.asana.com/0/1200268243113852/1202676002018771
=> [Feat]: Social icons and link

src/components/SidebarMenu/index.js
STORY: https://app.asana.com/0/1198717964402573/1202714062882750
=> Hide appointments for driver managers

src/components/Marketing/CampaignAmountOption/index.js
Story: https://app.asana.com/0/1200268243113852/1202473893483672
=> Update: marketing

src/components/Orders/Messages/index.js
Story: https://app.asana.com/0/1199511033583011/1202541961761827/f
Image: https://d.pr/i/h2VHav
=> [FEAT] logistic tags

src/components/Stores/BusinessInformation/index.js
Story: https://app.asana.com/0/1200268243113852/1202714062882767
=> Update: social network

src/components/OrderingProducts/OrderingProductDetails/index.js, src/components/OrderingProducts/OrderingProductDetails/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202175610551124
=> [Update] site details

src/components/Orders/DriverSelector/index.js, src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderDetails/index.js, src/components/Orders/OrdersManager/index.js
STORY: https://app.asana.com/0/1198717964402573/1202714030865815
=> [Update] drivers for order

src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/ProductExtraOptionDetails/styles.js, src/components/Stores/ProductExtraOptions/index.js, src/components/Stores/ProductExtraOptions/styles.js, src/components/Stores/ProductExtraSuboption/index.js, src/components/Stores/ProductExtraSuboption/styles.js, src/contexts/ThemeContext/index.js
STORY: https://app.asana.com/0/1198717964402573/1201187454932616
=> [Add] Drag and drop functionality for options rank

src/components/Orders/OrdersFilterGroup/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202626745621132
=> feedback status filter

src/components/Delivery/DriversGroupDetails/index.js, src/components/Delivery/DriversGroupGeneralForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1202784597860127
=> [Fix] Driver group feedback

src/components/Orders/OrdersTable/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202792368840123
Demo: https://d.pr/v/RCfZD6
=> improve order sla settings

src/components/Settings/SettingsList/index.js
Story:  https://app.asana.com/0/home/1200550251832815/1202799394390987
Demo: https://d.pr/v/QRW90n
=> platform fee set zero

src/components/Orders/DriversList/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202808937620949
=> [Fix] style issue

src/components/Settings/CountriesList/index.js, src/components/Settings/CountriesList/styles.js, src/components/Settings/CountryDetails/index.js, src/components/Settings/CountryDetails/styles.js, src/components/Settings/CountrySettingDetail/index.js, src/components/Settings/CountrySettingDetail/styles.js, src/components/Settings/MultiCountrySettings/index.js, src/components/Settings/MultiCountrySettings/styles.js, src/components/Settings/PlaceListing/index.js, src/components/Settings/PlaceListing/styles.js, src/components/Settings/Settings/index.js
Story: https://app.asana.com/0/1200268243113852/1202821858758610
=> Update: Multi country

src/components/LanguageSelector/index.js, src/components/Settings/LanguageSetting/index.js
Story: https://app.asana.com/0/1199511033583011/1202309733876263/f
Video: https://d.pr/v/cTHknw
=> [FIX] language default selector

src/components/LanguageSelector/index.js
Story: https://app.asana.com/0/1199511033583011/1202309733876263/f
Video: https://d.pr/v/ahyIa8
=> [FIX] Language permissions

src/components/Orders/OrdersTable/index.js, src/components/Orders/OrdersTable/styles.js, src/components/Users/UsersList/index.js, src/components/Users/UsersList/styles.js
Story: https://app.asana.com/0/1200268243113852/1202772229135989
=> Update: orders count

src/components/DisabledFeatureAlert/index.js, src/components/DisabledFeatureAlert/styles.js, template/app.js
Story: https://app.asana.com/0/home/1200550251832815/1202815760455843
Demo: https://d.pr/v/NEgei7
=> dashboard block feature

src/components/Marketing/EnterprisePromotionConditions/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202830454215953
Demo: https://d.pr/v/kmJBXJ
=> allow uncheck promotion

src/components/Stores/EditTaxManager/index.js
STORY: https://app.asana.com/0/inbox/1198717964396322/1202840375626115/1202892510363929
=> [Fix] tax and fee validation

src/components/Stores/index.js, src/index.js
story: https://app.asana.com/0/1201324366625225/1202882948328314/f
=> [FEAT] Add missing imports

src/components/Marketing/EnterprisePromotionList/index.js, src/components/Marketing/EnterprisePromotionList/styles.js
Story: https://app.asana.com/0/home/1200550251832815/1202871188266861
Demo: https://d.pr/v/34xUX4, https://d.pr/v/kQLc3Y
=> update promotion rank

src/components/Marketing/EnterprisePromotionList/index.js, src/components/Marketing/EnterprisePromotionList/styles.js
Story: https://app.asana.com/0/home/1200550251832815/1202871188266861
Demo: https://d.pr/v/fmEwSS
=> improve promotion rank move

src/components/BusinessIntelligence/AnalyticsProductCategories/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202918732485183
Demo: https://d.pr/i/8doQy3
=> Reports fixes

src/components/Orders/CountryFilter/index.js, src/components/Orders/CountryFilter/styles.js, src/components/Orders/OrdersFilterGroup/index.js, src/components/Orders/index.js
Story: https://app.asana.com/0/1200268243113852/1202917724844242
=> [Feat]: multi currency

src/components/OrderingProducts/SiteTheme/ThemeComponent.js
STORY: https://app.asana.com/0/1198717964402573/1202210919869674
=> [Update] theme image

src/components/OrderingProducts/OrderingProductsListing/index.js, src/components/OrderingProducts/OrderingProductsListing/styles.js, src/components/OrderingProducts/SiteTheme/ThemeComponent.js, src/components/OrderingProducts/SiteTheme/ThemeImage.js, src/components/OrderingProducts/SiteTheme/ThemeOption.js, src/components/OrderingProducts/SiteTheme/index.js, src/components/OrderingProducts/SiteTheme/styles.js
STORY: https://app.asana.com/0/1198717964402573/1202965291068061
=> [Fix] Layout settings feedback

src/components/Orders/OrdersListing/index.js, src/components/Orders/OrdersTable/index.js, src/components/Shared/ColumnAllowSettingPopover/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202822050247341
Demo: https://d.pr/v/1FCYdr
=> improve order manager

src/components/Orders/DeliveriesLocation/index.js, src/components/Orders/DriversLocation/index.js
STORY: https://app.asana.com/0/1198717964402573/1203006460034832
=> [Fix] driver location issue

src/components/OrderingProducts/SiteTheme/ThemeComponent.js, src/components/OrderingProducts/SiteTheme/index.js
STORY: https://app.asana.com/0/1198717964402573/1203005671215228
=> [Fix] ordering theme setting crash

src/components/SidebarMenu/index.js, template/app.js
Story: https://app.asana.com/0/1200268243113852/1202982425553847
=> Update: admin update

src/components/Orders/CurrencyFilter/index.js, src/components/Orders/OrderBill/index.js, src/components/Orders/OrderDetails/index.js, src/components/Orders/OrdersTable/index.js, src/components/Orders/ProductItemAccordion/index.js, src/config/constants.js
Story: https://app.asana.com/0/1200268243113852/1203016721634873
=> Update: multi currency feedback

src/components/Shared/SearchBar/index.js, src/components/Stores/BusinessProductList/index.js, src/components/Stores/BusinessProductsCategories/index.js, src/components/Stores/BusinessProductsListing/index.js, src/components/Stores/BusinessProductsListing/styles.js, src/components/Stores/BusinessesListing/index.js, src/components/Stores/BusinessesListingHeader/index.js, src/components/Stores/BusinessesListingHeader/styles.js, src/components/Stores/ImportersButton/index.js, src/components/Stores/ImportersButton/styles.js
Story: https://app.asana.com/0/home/1200550251832815/1202938731260382
Demo: https://d.pr/v/tJn5p2, https://d.pr/i/duVzIF
=> add refresh functionality in business

src/components/Login/LoginForm/index.js
Story: https://app.asana.com/0/home/1200550251832815/1202895355715695
=> bug recaptcha v3

src/components/BusinessIntelligence/Reports/index.js, src/components/BusinessIntelligence/Reports/styles.js, src/components/Delivery/DriversGroupDetails/index.js, src/components/DisabledFeatureAlert/index.js, src/components/DisabledFeatureAlert/styles.js, src/components/Loyalty/RewardsPrograms/index.js, src/components/Loyalty/RewardsPrograms/styles.js, src/components/Settings/Settings/index.js, src/components/Settings/SettingsDetail/index.js, src/components/Settings/SettingsDetail/styles.js, src/components/SidebarMenu/index.js, src/components/Stores/BusinessMenuOptions/index.js, src/components/Stores/ImportersButton/index.js, src/components/Stores/ImportersButton/styles.js, src/components/Stores/ImportersList/index.js, src/components/Stores/ImportersList/styles.js, src/components/Stores/ImportersListing/index.js, template/app.js
Story: https://app.asana.com/0/home/1200550251832815/1202815760455843
=> Dashboard block features

src/components/Orders/GiftCardsListing/index.js, src/components/Orders/GiftCardsListing/styles.js, src/components/SidebarMenu/index.js
STORY: https://app.asana.com/0/1198717964402573/1202976229479472
=> Feedback gift cards

src/components/Stores/EditTaxManager/index.js
STORY: https://app.asana.com/0/inbox/1198717964396322/1202899363956286/1202902521280673
=> [Update] percentage validation

src/components/Stores/SeoOptions/index.js, src/components/Stores/SeoOptions/styles.js
Story: https://app.asana.com/0/1200268243113852/1203048990397070
=> Update: product seo

src/components/Settings/LanguageSetting/index.js, src/components/Settings/LanguageSetting/styles.js
Story: https://app.asana.com/0/1200268243113852/1203038786166496
=> Update: avoid disabled language

src/components/SidebarMenu/index.js, template/app.js
Story: https://app.asana.com/0/1200268243113852/1203076693142912
=> Update: show drivers for business owner

src/components/Orders/DeliveriesLocation/index.js, src/components/Orders/DriversLocation/index.js
STORY: https://app.asana.com/0/1198717964402573/1202981354221777
=> [Update] default location

src/components/Stores/ProductDetails/index.js, src/components/Stores/ProductMainDetails/index.js, src/components/Stores/SeoOptions/index.js
Story: https://app.asana.com/0/1200268243113852/1203081496079116
=> Update: product SEO feedback

src/components/Stores/ProductDetatilsInformation/index.js
STORY: https://app.asana.com/0/1198717964402573/1203092888901359
=> Disable auto generate slug button

src/components/BusinessIntelligence/Reports/index.js, src/components/BusinessIntelligence/Reports/styles.js, src/components/Loyalty/RewardsPrograms/index.js, src/components/Loyalty/RewardsPrograms/styles.js, src/components/Marketing/CampaignHeader/index.js, src/components/Marketing/CampaignHeader/styles.js, src/components/Marketing/CampaignList/index.js, src/components/Marketing/CampaignList/styles.js, src/components/Marketing/CampaignListing/index.js, src/components/Settings/SettingsDetail/index.js, src/components/Settings/SettingsDetail/styles.js, src/components/Settings/SettingsList/index.js, src/components/Stores/BusinessMenu/index.js, src/components/Stores/BusinessMenu/styles.js, src/components/Stores/BusinessPaymentMethods/index.js, src/components/Stores/ImportersList/index.js, src/components/Stores/ImportersList/styles.js, src/components/Stores/ImportersListing/index.js, src/components/Stores/PaymentOption/index.js, src/components/Stores/PaymentOptionMethods/index.js, src/components/Stores/PaymentOptionPaypal/index.js, src/components/Stores/PaymentOptionSquare/index.js, src/components/Stores/PaymentOptionStripeDirect/index.js, src/components/Stores/PaymentOptionStripeDirect/styles.js, src/components/Stores/PaymethodOptionPaypalExpress/index.js, src/components/Stores/PaymethodOptionStripeConnect/index.js, src/components/Stores/PaymethodOptionStripeRedirect/index.js
Story: https://app.asana.com/0/1200268243113852/1203093662884241
=> Update: unlock block functionality

src/components/Stores/ProductExtraOptionForm/index.js, template/config.json
STORY: https://app.asana.com/0/1198717964402573/1203123651501978
=> [Fix] product option enable function

src/components/Orders/OrderDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203102112447535
=> disable load messages

src/components/Stores/BusinessProductsCategoyInfo/index.js, src/components/Stores/ProductDetatilsInformation/index.js
STORY: https://app.asana.com/0/1198717964402573/1203150565292074
=> [Fix] Product and Category slug

src/components/Stores/BusinessProductAddForm/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203158720453506
=> [Fix] Firefox issue when adding product

src/components/Loyalty/PointsWalletLevels/index.js, src/components/Loyalty/PointsWalletLevels/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203145730294722
=> [Fix] loyalty levels Notfound style issue

src/components/Stores/BusinessSync/index.js, src/components/Stores/BusinessSyncBasic/index.js, src/components/Stores/BusinessSyncBasic/styles.js
Story: https://app.asana.com/0/1200268243113852/1202786348070583
=> Update: sync button

src/components/Stores/SeoOptions/index.js
PR: https://app.asana.com/0/1199511033583011/1203185611136705/f
Video: https://d.pr/v/AxdyxM
=> [FEAT] business&category improvement

src/components/Orders/index.js, src/index.js
Story: https://app.asana.com/0/1201324366625225/1203197936378643/f
=> [FEAT] export components

src/index.js
=> [FEAT] Missed change

src/components/Stores/index.js, src/components/Users/index.js, src/index.js
Story: https://app.asana.com/0/1201324366625225/1203207196837064/f
=> [FEAT] Add missing exports

src/components/Stores/BusinessInformation/index.js, src/components/Stores/BusinessProductsCategoyInfo/index.js, src/components/Stores/BusinessProductsCategoyInfo/styles.js, src/components/Stores/ProductDetatilsInformation/index.js
STORY: https://app.asana.com/0/1198717964402573/1203207801758809
=> [Add] External Id

src/components/Stores/SeoOptions/index.js
Story: https://app.asana.com/0/1200268243113852/1203081496079116
=> Update: seo option

src/components/Delivery/UserFormDetails/index.js, src/components/Orders/OrdersTable/index.js, src/components/Shared/ColumnAllowSettingPopover/index.js, src/components/Stores/BusinessProductsListing/index.js, src/components/Users/CustomerDetails/index.js, src/components/Users/CustomersListing/index.js, src/components/Users/ProfessionalDetail/index.js, src/components/Users/ProfessionalList/index.js, src/components/Users/ProfessionalList/styles.js, src/components/Users/ProfessionalListing/index.js, src/components/Users/UserDetails/index.js, src/components/Users/UsersList/index.js, src/components/Users/UsersList/styles.js, src/components/Users/UsersListing/index.js
Story: https://app.asana.com/0/1200268243113852/1203051766155813
=> [Update]: Dashboard feedback

src/components/OrderingProducts/SiteTheme/index.js
Story: https://app.asana.com/0/1200268243113852/1203245427225059
=> Update: theme

src/components/Settings/SettingsSelectUI/index.js
STORY: https://app.asana.com/0/1198717964402573/1203230261451308
=> [Fix] Wrong language default value

src/components/Login/ResetPassword/index.js, src/components/Login/ResetPassword/styles.js, src/components/Login/index.js, src/index.js, template/app.js, template/components/ListenPageChanges/index.js, template/helmetdata.json, template/pages/ResetPassword/index.js
Story: https://app.asana.com/0/1199511033583011/1203237884370429/f
Video: https://d.pr/v/QhQzkB
=> [FEAT] password reset improvement

src/components/Stores/PaymentOption/index.js, src/components/Stores/PaymentOptionMethods/index.js, src/components/Stores/PaymentOptionPaypal/index.js, src/components/Stores/PaymentOptionStripeDirect/index.js, src/components/Stores/PaymethodOptionPaypalExpress/index.js, src/components/Stores/PaymethodOptionStripeConnect/index.js
Story: https://app.asana.com/0/1199511033583011/1203235719050223/f
Video: https://d.pr/v/mOBpRN
=> [FEAT] Fix blank flickering bug

src/components/Stores/BusinessLocation/index.js
STORY: https://app.asana.com/0/1198717964402573/1203137845562288
=> disable auto fill by 1Password extension

src/components/Orders/Messages/index.js
STORY: https://app.asana.com/0/1198717964402573/1203254334997750
=> [Fix] log by vehicle

src/components/Stores/PaymentOption/index.js, src/components/Stores/PaymentOptionMethods/index.js, src/components/Stores/PaymentOptionPaypal/index.js, src/components/Stores/PaymentOptionStripeDirect/index.js, src/components/Stores/PaymethodOptionPaypalExpress/index.js, src/components/Stores/PaymethodOptionStripeConnect/index.js, src/components/Stores/PaymethodOptionStripeRedirect/index.js
Story: https://app.asana.com/0/0/1203270603383666/f
=> [FEAT] feedback fix for channels

src/components/Stores/BusinessWebhooks/index.js
STORY: https://app.asana.com/0/1198717964402573/1203269656847313
=> [Fix] webhook delete issue

src/components/Profile/ProfilePage/index.js, src/components/Profile/ProfilePage/styles.js, src/components/Profile/Sessions/index.js, src/components/Profile/Sessions/styles.js, src/components/Profile/index.js
Story: https://app.asana.com/0/1200268243113852/1203144119299013
=> [Feat]: Session management

src/components/Login/ResetPassword/index.js
Story: https://app.asana.com/0/0/1203281381299352/f
=> [FEAT] disable autocomplete

src/components/Marketing/CampaignEmail/index.js, src/components/Marketing/CampaignNotification/index.js, src/components/Marketing/CampaignSMS/index.js
Story: https://app.asana.com/0/1200268243113852/1203321603294829
=> Update: setting link

src/components/CartRecovery/OpenCartsFilterGroup/index.js, src/components/Marketing/CampaignSignUpOption/index.js, src/components/Profile/Sessions/index.js, src/components/Profile/Sessions/styles.js, src/components/Shared/Modal/index.js, src/components/Shared/Modal/styles.js
Story: https://app.asana.com/0/1200268243113852/1203321603294823
=> [Update]: sessions

src/components/Orders/OrderDetails/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203302923993160
=> [Fix] order detail style issue

src/components/Stores/BusinessDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203193062372208
=> [Fix] Shared store deleting issue

src/components/Delivery/DriversGroupLogs/index.js
STORY: https://app.asana.com/0/1198717964402573/1203312916207104
=> [Fix] drivers group log

src/components/SidebarMenu/index.js, src/components/SidebarMenu/styles.js, src/components/Stores/BusinessProductList/styles.js, src/components/Stores/BusinessProductsCategories/styles.js, src/components/Stores/BusinessProductsListing/index.js, src/components/Stores/BusinessProductsListing/styles.js, src/components/Stores/BusinessSummary/index.js, src/components/Stores/BusinessSummary/styles.js, src/utils/index.js
Story: https://app.asana.com/0/1200268243113852/1203301857571526
=> [Feat]: visit market

src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrdersManager/index.js
STORY: https://app.asana.com/0/1198717964402573/1203006460034838
=> [Fix] driver auto assign issue

src/components/Login/LoginForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1203329146101973
=> [Fix] Email OTP issues

template/app.js
Story: https://app.asana.com/0/1200268243113852/1203328289238748
=> Update: appointments for business owner

src/components/Marketing/EnterprisePromotionDetails/index.js, src/components/Shared/SelectUsers/index.js, src/components/SidebarMenu/index.js
story: https://app.asana.com/0/1203068399720324/1203301857571516
demo: https://www.loom.com/share/2fd8b55814aa4aeb9db55d955098b4ad
=> [Add] marketing promotion: users, filter

src/components/SidebarMenu/index.js, src/components/Stores/BusinessProductsListing/index.js, src/components/Stores/BusinessSummary/index.js
Story: https://app.asana.com/0/1200268243113852/1203301857571526
=> Update: visit marketing

src/components/Stores/BusinessDeliveryZoneInformation/index.js
story: https://app.asana.com/0/1203068399720324/1203331637208866
demo: https://www.loom.com/share/2f24ccb110884c17943110fd4fd45d57
=> [Update] disable name, type & zone when deliveryzone its shared

src/components/Settings/Settings/index.js
STORY: https://app.asana.com/0/inbox/1198717964396322/1203364915783379/1203376110609378
=> Delete multi country and sites settings

src/components/MyProducts/ContentForm/index.js, src/components/MyProducts/OrderingWebsite/index.js
Story: https://app.asana.com/0/home/1200268243109536/1203391689620543
=> Update: ordering endpoint

src/components/OrderingProducts/SiteTheme/index.js, src/components/OrderingProducts/SiteTheme/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203392868408951
=> [Add] hidden checkbox

src/components/Orders/OrdersManager/index.js
STORY: https://app.asana.com/0/1198717964402573/1203356529495484
=> Update for speed improvements

src/components/Home/HomePage/index.js, src/components/Home/HomePage/styles.js, src/components/MyProducts/ContentForm/index.js, src/components/MyProducts/OrderingWebsite/index.js, src/components/MyProducts/OrderingWebsite/styles.js
Story: https://app.asana.com/0/1200268243113852/1203402810187080
=> Update: ordering product

src/components/MyProducts/ContentForm/index.js, src/components/MyProducts/OrderingWebsite/index.js, src/components/MyProducts/OrderingWebsite/styles.js, src/components/SidebarMenu/index.js
Story: https://app.asana.com/0/1200268243113852/1203407611474443
=> Update: ordering website

src/components/SidebarMenu/index.js
https://app.asana.com/0/1199511033583011/1203434216439211/f
=> [FEAT unhide ordering products

src/components/BusinessIntelligence/CountryFilter/index.js
Story: https://app.asana.com/0/1200268243113852/1203385190545605
=> Update: country popup feedback

src/components/Settings/LalamoveConnect/styles.js
Story: https://app.asana.com/0/1200268243113852/1203439452995175
=> Update: font style on LalaMove

src/components/Orders/OrderBill/index.js
story: https://app.asana.com/0/0/1203447465703981/f
demo: https://www.loom.com/share/99cee2644a44421996f5abbd1ada0cb7
=> [Fix] delivery option when default is selected

src/components/Stores/PaymentOptionMethods/index.js, src/components/Stores/PaymentOptionMethods/styles.js, src/components/Stores/PaymentOptionPaypal/index.js, src/components/Stores/PaymentOptionPaypal/styles.js, src/components/Stores/PaymentOptionSquare/index.js, src/components/Stores/PaymentOptionStripeDirect/index.js, src/components/Stores/PaymentOptionStripeDirect/styles.js, src/components/Stores/PaymethodOptionPaypalExpress/index.js, src/components/Stores/PaymethodOptionPaypalExpress/styles.js, src/components/Stores/PaymethodOptionStripeRedirect/index.js, src/components/Stores/PaymethodOptionStripeRedirect/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203445998350919
=> [Fix] payment sandbox issue

src/components/Marketing/AdBannersListing/index.js, src/components/Marketing/AdBannersListing/styles.js, src/components/Marketing/BannerDetails/BannerImages.js, src/components/Marketing/BannerDetails/styles.js, src/components/Marketing/PageBanner/index.js, src/components/Marketing/PageBanner/styles.js, src/components/Shared/ImageCrop/index.js
STORY: https://app.asana.com/0/1198717964402573/1203458248409508
=> Page banner feedback

src/components/Stores/BusinessWidgets/index.js, src/components/Stores/BusinessWidgets/styles.js
Story: https://app.asana.com/0/1200268243113852/1203461396657485
=> [UPDATE]: widgets section on ordering channel

src/components/BusinessIntelligence/AnalyticsDriverOrders/index.js, src/components/BusinessIntelligence/AnalyticsOrdersOrSales/index.js, src/components/BusinessIntelligence/BusinessAnalytics/index.js, src/components/BusinessIntelligence/DriverAnalytics/index.js
Story: https://app.asana.com/0/1200268243113852/1203465927226229
=> [UPDATE]: hide currency on country filter

src/components/Delivery/DriversGroupDeliveryZoneInformation/index.js, src/components/Stores/BusinessDeliveryZoneInformation/index.js, src/components/Stores/BusinessDeliveryZoneInformation/styles.js
story: https://app.asana.com/0/0/1203452022329015/f
demo: https://www.loom.com/share/402f35f43b2c475db419f4da40d3f79b
=> feedback fixes

src/components/Stores/ImporterForm/index.js, src/components/Stores/ImporterJobForm/index.js, src/components/Stores/ImportersListing/index.js
Story: https://app.asana.com/0/1199511033583011/1203138605690722/f
Video: https://d.pr/v/HJ4Si2
=> [FEAT] Don't send empty keys

src/components/Stores/BusinessDelete/index.js, src/components/Stores/BusinessDelete/styles.js, src/components/Stores/BusinessesList/index.js, src/components/Stores/BusinessesList/styles.js, src/components/Stores/BusinessesListing/index.js, src/components/Stores/BusinessesListing/styles.js, src/components/Stores/SingleBusiness/index.js, src/components/Stores/SingleBusiness/styles.js, src/components/Stores/index.js
Story: https://app.asana.com/0/1200268243113852/1202938695872610
=> [UPDATE]: business multi select

src/components/Marketing/AdBannersListing/index.js, src/components/Marketing/PageBanner/index.js, src/components/Marketing/PageBanner/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203458248409508
=> [Fix] Page banner feedback

src/components/MyProducts/OrderingWebsite/index.js
Story: https://app.asana.com/0/1200268243113852/1203449320720243
=> [ADD]: mobile image on MyProducts

src/components/Loyalty/GiftCardDetail/index.js, src/components/Loyalty/GiftCardDetail/styles.js, src/components/Loyalty/GiftCards/index.js, src/components/Loyalty/GiftCards/styles.js, src/components/Loyalty/RewardsPrograms/index.js
STORY: https://app.asana.com/0/1198717964402573/1203422541705642
=> [Feat] Gift cards

src/components/Orders/OrderDetails/index.js, src/components/Orders/OrdersTable/index.js, src/components/Stores/BusinessDeliveryPickupMore/index.js, src/components/Stores/BusinessDeliveryPickupMore/styles.js, src/components/Stores/BusinessEta/index.js, src/components/Stores/BusinessEta/styles.js, yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202956174747201
=> [Add] ETA's functionality

index-template.js
story: https://app.asana.com/0/1199511033583011/1202891054799701/f
=> Sentry update config

src/components/Marketing/BannerDetails/index.js, src/components/Marketing/BannerDetails/styles.js
STOROY: https://app.asana.com/0/1198717964402573/1203534285264028
=> [Add] banner name change

src/components/Orders/OrderBill/index.js
story: https://app.asana.com/0/1199511033583011/1203515954282641/f
demo: https://www.loom.com/share/f50226d80f864ba3ba54e0d97021ea6b
=> key_langs for curbside

src/components/Settings/Settings/index.js
STORY: https://app.asana.com/0/1198717964402573/1203549200231296
=> [Add] multi country setting validation

src/components/Stores/BusinessEta/index.js
STORY: https://app.asana.com/0/1198717964402573/1203547429694256
=> [Add] status 23

src/components/Marketing/CampaignUsersList/index.js
Story: https://app.asana.com/0/1200268243113852/1203523161717588
=> [update]: marketing users

src/components/Stores/BusinessProductsListing/index.js, src/components/Stores/ProductStep/index.js, src/components/Stores/RestaurantSelectGuide/index.js
Story: https://app.asana.com/0/home/1200268243109536/1203473061868366
=> [Update]: Ordering network 

src/components/MyProducts/AppLayout/index.js, src/components/MyProducts/CallCenterApp/index.js, src/components/MyProducts/CustomerApp/index.js, src/components/MyProducts/DriverApp/index.js, src/components/MyProducts/KioskApp/index.js, src/components/MyProducts/PosApp/index.js, src/components/MyProducts/StoreApp/index.js, src/utils/index.js
Story: https://app.asana.com/0/1200268243113852/1203546200408658
=> [Update]: show always intercom chat

src/components/Stores/BusinessAdd/BusinessDetails/index.js, src/components/Stores/BusinessAdd/DeliveryZone/styles.js, src/components/Stores/BusinessAdd/ReceiveOrders/styles.js, src/components/Stores/BusinessAdd/styles.js, src/components/Stores/BusinessProductsListing/index.js, src/components/Stores/ProductStartGuide/index.js, src/components/Stores/ProductStartGuide/styles.js, src/components/Stores/ProductStep/index.js, src/components/Stores/RestaurantSelectGuide/index.js
Story: https://app.asana.com/0/1200268243113852/1203557719626222
=> [Fix]: ordering network

src/components/Stores/BusinessAdd/BusinessDetails/index.js, src/components/Stores/BusinessAdd/Photos/index.js, src/components/Stores/BusinessAdd/Schedule/index.js, src/components/Stores/BusinessAdd/index.js, src/components/Stores/BusinessAdd/styles.js, src/components/Stores/BusinessAddStore/index.js, src/components/Stores/BusinessAddStore/styles.js, src/components/Stores/BusinessesListing/index.js, src/utils/index.js, template/pages/BusinessAdd/index.js
Story: https://app.asana.com/0/1200268243113852/1203564492881721
=> [Feat]: ordering network 3

src/components/Orders/OrdersTable/index.js
=> [FEAT] fix-order-column-filter

src/components/BusinessIntelligence/BusinessReviewList/index.js, src/components/BusinessIntelligence/UsersReviewList/index.js, src/components/Delivery/DriversGroupDeliveryZoneInformation/index.js, src/components/Delivery/DriversGroupDetails/index.js, src/components/Delivery/DriversGroupsDeliveryZoneDetails/index.js, src/components/Delivery/UsersList/index.js, src/components/OrderingProducts/OrderingProductsListing/index.js, src/components/SidebarMenu/index.js, src/components/SidebarMenu/styles.js, src/components/Stores/BusinessProductAddForm/index.js, src/components/Stores/BusinessesList/index.js, src/components/Users/ProfessionalList/index.js, src/components/Users/UsersList/index.js
Story: https://app.asana.com/0/1200268243113852/1203422541705554
=> [update]: feedback

src/components/Marketing/AdBannersListing/index.js, src/components/Marketing/BannerDetails/BannerImages.js, src/components/Marketing/BannerDetails/index.js, src/components/Marketing/BannerDetails/styles.js, src/components/Marketing/BannerImageLink/BusinessLink.js, src/components/Marketing/BannerImageLink/ProductLink.js, src/components/Marketing/BannerImageLink/SelectBusinessProducts/index.js, src/components/Marketing/BannerImageLink/SelectBusinessProducts/styles.js, src/components/Marketing/BannerImageLink/index.js, src/components/Marketing/BannerImageLink/styles.js, src/components/Marketing/PageBanner/index.js
STORY: https://app.asana.com/0/1198717964402573/1201051528393155
=> [Add] Page banner link

src/components/Profile/ProfilePage/index.js, src/components/Profile/ProfilePage/styles.js, src/components/Users/ProfessionalAddForm/index.js, src/components/Users/ProfessionalListing/index.js, src/components/Users/ProfessionalSchedule/Schedule/index.js, src/components/Users/ProfessionalSchedule/index.js, src/components/Users/ProfessionalSchedule/styles.js, src/components/Users/UsersListingHeader/index.js, src/components/Users/UsersListingHeader/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203608052739044
=> [Improve] Appointments

src/components/Users/UsersList/index.js
STORY: https://app.asana.com/0/1198717964402573/1203595177996063
=> [Fix] pagination issue for users

src/components/Shared/Modal/styles.js
story: https://app.asana.com/0/1199511033583011/1203569533484758/f
demo: https://www.loom.com/share/626463c0511948c4a57060c4b55dbce7
=> [Fix] modal did not scroll when addidng several options

src/components/Orders/Appointments/index.js, src/components/Orders/Appointments/styles.js, src/components/Stores/BusinessProductAddForm/index.js, src/components/Users/ProfessionalListing/index.js, src/components/Users/ProfessionalListing/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203580203471892
=> [Add] validation by the appointments feature

src/components/Orders/Appointments/EventComponent.js, src/components/Orders/Appointments/index.js, src/components/Orders/ProductItemAccordion/index.js, src/components/Orders/ProductItemAccordion/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203580203471898
=> [Fix] appointment time issue

src/components/SidebarMenu/index.js
STORY: https://app.asana.com/0/1198717964402573/1203580203471887
=> Professionals feedback

src/components/Settings/DoordashConnect/index.js
Story: https://app.asana.com/0/0/1203332995878424/f
=> [FEAT] add australia and canada

src/components/Orders/OrdersTable/styles.js
Story: https://app.asana.com/0/0/1203613494326007/f
=> [FEAT] feedback

src/components/Settings/EmailSetting/index.js
STORY: https://app.asana.com/0/1198717964402573/1203595541420209
=> [Add] Email new settings

src/components/Settings/IntegrationListing/index.js
Story: https://app.asana.com/0/1199511033583011/1203614338531599/f
=> [FEAT] Lalamove

src/components/Settings/index.js, src/components/Stores/index.js, src/index.js
Story: https://app.asana.com/0/1201324366625225/1203626598698533/f
=> [FEAT] missing imports

src/components/SidebarMenu/index.js
STORY: https://app.asana.com/0/1198717964402573/1203626544049945
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1203643182943878
=> [Add] validation for appoints module

src/components/Stores/ProductStep/index.js, src/components/Stores/ProductStep/styles.js, src/components/Stores/UploadMenuGuide/index.js
Story: https://app.asana.com/0/1200268243113852/1203658063963165
=> [Update]: store network

src/components/Stores/BusinessAdd/BusinessDetails/index.js
Story: https://app.asana.com/0/inbox/1200268243109536/1203658063963186/1203664495531693
=> [Update]: phone number name

src/components/BusinessIntelligence/BusinessReviewList/styles.js, src/components/BusinessIntelligence/UsersReviewList/styles.js, src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderDetails/styles.js, src/components/Stores/BusinessProductList/styles.js, src/components/Stores/BusinessesList/styles.js, src/components/Users/ProfessionalList/styles.js, src/components/Users/UsersList/index.js, src/components/Users/UsersList/styles.js
Story: https://app.asana.com/0/1200268243113852/1203402810187130
=> [Fix]: intercom bubble

src/components/Delivery/UserDetails/index.js, src/components/Delivery/UserDetails/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203664176854272
=> [Fix] Driver Schedule Enable

src/components/Settings/Settings/index.js
STORY: https://app.asana.com/0/1198717964402573/1203287387352418
=> [Add] site configs setting

src/components/Delivery/DriversCompaniesList/styles.js, src/components/Delivery/DriversGroupsList/styles.js, src/components/Delivery/UsersList/styles.js, src/components/Orders/DeliveryDashboard/styles.js, src/components/Orders/DriversDashboard/styles.js
Story: https://app.asana.com/0/1200268243113852/1203674406369096
=> [Bug]: intercom bubble feedback

src/components/Marketing/EnterprisePromotionList/index.js, src/components/Marketing/EnterprisePromotionList/styles.js, src/components/Settings/Cms/styles.js
Story: https://app.asana.com/0/1200268243113852/1203674406369096
=> [Fix]: intercom bubble feedback

src/components/Stores/PaymentOption/index.js
story: https://app.asana.com/0/1199511033583011/1203676309902211/f
demo: https://d.pr/v/nYqiiJ
=> [Add] all check

src/components/Shared/ColumnAllowSettingPopover/styles.js
Story: https://app.asana.com/0/0/1203689317229044/f
Video:
https://d.pr/v/ZsZWy6
=> [FEAT] make popup filter floating

src/components/Settings/SettingsList/index.js, src/components/Settings/SettingsList/styles.js, src/components/Settings/SettingsSelectUI/index.js
Story: https://app.asana.com/0/inbox/1200268243109536/1202884440211658/1203483795364101
=> [Add]: Guest checkout setting

src/components/Settings/CountriesList/styles.js, src/components/Settings/LanguageTransTable/styles.js
Story: https://app.asana.com/0/1200268243113852/1203674406369096
=> [Fix]: Intercom bubble on language manager

src/components/BusinessIntelligence/AnalyticsSpendList/styles.js, src/components/BusinessIntelligence/ReportsAverageSales/styles.js, src/components/BusinessIntelligence/ReportsBusinessDistance/styles.js, src/components/BusinessIntelligence/ReportsBusinessSpend/styles.js, src/components/BusinessIntelligence/ReportsCustomer/styles.js, src/components/BusinessIntelligence/ReportsDriverDistance/styles.js, src/components/BusinessIntelligence/ReportsDriverOrder/styles.js, src/components/BusinessIntelligence/ReportsDriverOrderTime/styles.js, src/components/BusinessIntelligence/ReportsDriverSchedule/styles.js, src/components/BusinessIntelligence/ReportsDriverSpend/styles.js, src/components/BusinessIntelligence/ReportsGeneralSales/styles.js, src/components/BusinessIntelligence/ReportsHeatMap/styles.js, src/components/BusinessIntelligence/ReportsOrderDistance/styles.js, src/components/BusinessIntelligence/ReportsOrderStatus/styles.js, src/components/BusinessIntelligence/ReportsOrders/styles.js, src/components/BusinessIntelligence/ReportsPaymethodSales/styles.js, src/components/BusinessIntelligence/ReportsSaleAndCategory/styles.js, src/components/BusinessIntelligence/ReportsSales/styles.js, src/components/BusinessIntelligence/ReportsSpentTIme/styles.js, src/components/BusinessIntelligence/ReportsTopDrivers/styles.js, src/components/BusinessIntelligence/ReportsUsers/styles.js
Story: https://app.asana.com/0/1200268243113852/1203705277812607
=> [Update]: optmize responsive feedback

src/components/MyProducts/AdvancedSettings/FontStyleGroup.js, src/components/MyProducts/AdvancedSettings/ImageBox.js, src/components/MyProducts/AdvancedSettings/OrderType.js, src/components/MyProducts/AdvancedSettings/SettingComponent.js, src/components/MyProducts/AdvancedSettings/index.js, src/components/MyProducts/AdvancedSettings/styles.js, src/components/MyProducts/OrderingWebsite/index.js, src/components/MyProducts/OrderingWebsite/styles.js
Story: https://app.asana.com/0/1200268243113852/1203476743671995
=> [Feat]: advanced settings in ordering website

src/components/Users/OccupationSelector/index.js, src/components/Users/OccupationSelector/styles.js, src/components/Users/OccupationsFilter/index.js, src/components/Users/OccupationsFilter/styles.js, src/components/Users/ProfessionalAddForm/index.js, src/components/Users/ProfessionalListing/index.js, src/styles/Select/index.js, template/pages/Professionals/index.js
STORY: https://app.asana.com/0/1198717964402573/1203658063963189
=> [Update] Appointments functionality

src/components/MyProducts/AdvancedSettings/index.js, src/components/MyProducts/AppLayout/index.js, src/components/MyProducts/AppResources/index.js, src/components/MyProducts/AppResources/styles.js, src/components/MyProducts/CustomerApp/index.js, src/components/MyProducts/CustomerApp/styles.js
Story: https://app.asana.com/0/1200268243113852/1203476657810877
=> [Update]: Personalization customer app

src/components/Stores/BusinessDeliveryZoneDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203750856417297
=> [Fix] delivery zone share issue

src/components/Orders/OrderDetailsHeader/index.js
story: https://app.asana.com/0/1199511033583011/1203793432679627/f
=> [Fix] stripe link payment with multibusiness checkout

src/components/Orders/OrderContactInformation/index.js
Story: https://app.asana.com/0/1200268243113852/1203820032989926
=> [Bug] Guest user name as default on order detail

src/components/Stores/BusinessWalletsList/index.js
story: https://app.asana.com/0/1199511033583011/1203790302222655/f
=> [Add] wallets key_langs

src/components/Marketing/AdBannersListing/index.js
STORY: https://app.asana.com/0/1198717964402573/1203790174022634
=> Hide banner app home

src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/ProductExtraOptions/index.js, src/components/Stores/ProductExtraSuboption/index.js, src/components/Stores/ProductExtras/index.js, src/components/Stores/ProductOptionExternalId/index.js, src/components/Stores/ProductOptionExternalId/styles.js
Story: https://app.asana.com/0/1200268243113852/1203823346677184
=> [Update]: externalId for product option, suboption

src/components/Marketing/EnterprisePromotionGeneralDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203705283552682
=> [Fix] promotion expiration

src/components/Stores/index.js, src/index.js
=> Add missed exports

src/components/MyProducts/AdvancedSettings/styles.js, src/components/MyProducts/AppLayout/index.js, src/components/MyProducts/AppLayout/styles.js, src/components/MyProducts/OrderingWebsite/index.js, src/components/MyProducts/OrderingWebsite/styles.js
Story: https://app.asana.com/0/1200268243113852/1203836943874478
=> [Update]: dashboard advanced setting

src/components/Orders/DateTypeSelector/index.js
STORY: https://app.asana.com/0/1198717964402573/1203839649374341
=> [Fix] date filter

src/components/Stores/BusinessesListing/index.js, src/components/Stores/BusinessesListing/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203857701871633
=> [Fix] no businesses issue

src/components/Orders/Messages/index.js
STORY: https://app.asana.com/0/1198717964402573/1203827976826217
=> [Fix] Messages are not marked as read

src/components/Stores/ProductTagDetails/styles.js, src/components/Stores/SeoOptions/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203857701873860
=> [Fix] Safari browser issue

src/components/Orders/Messages/index.js, src/components/Orders/Messages/styles.js
story: https://app.asana.com/0/1199511033583011/1203827976826203/f
=> [Fix] do not show message suggestions after order ends

src/components/Loyalty/RewardsPrograms/index.js, src/components/Loyalty/Wallet/index.js, src/components/Loyalty/Wallet/styles.js, src/components/Loyalty/index.js, src/index.js
Story: https://app.asana.com/0/1200268243113852/1203920759623349
=> [Update]: wallet settings

src/components/MyProducts/AdvancedSettings/index.js, src/components/MyProducts/CallCenterApp/index.js, src/components/MyProducts/CustomerApp/index.js, src/components/MyProducts/DriverApp/index.js, src/components/MyProducts/KioskApp/index.js, src/components/MyProducts/PosApp/index.js, src/components/MyProducts/StoreApp/index.js
Story: https://app.asana.com/0/1200268243113852/1203931178093508
=> [Update]: Language variables

src/components/Stores/BusinessAddStore/index.js, src/components/Stores/BusinessesListing/index.js, src/components/Stores/BusinessesListing/styles.js, src/components/Stores/BusinessesListingHeader/index.js
Story: https://app.asana.com/0/1200268243113852/1203895463599420
=> [Update]: feedback part3

src/components/Login/LoginForm/index.js, src/components/Login/LoginForm/styles.js
story: https://app.asana.com/0/1199511033583011/1203772754518181/f
=> [Feat] add sign up redirect on login form screen

src/components/Stores/SeoOptions/index.js
Story: https://app.asana.com/0/1200268243113852/1203867986521833
=> [Update]: seo options

src/components/BusinessIntelligence/UsersReviewList/index.js
Story: https://app.asana.com/0/1199511033583011/1203393932816098/f
Video: https://d.pr/v/hPsJym
=> [FEAT] fix header title

src/components/Marketing/BannerDetails/BannerImages.js, src/components/Marketing/BannerDetails/index.js, src/components/Marketing/BannerImageDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203939728081129
=> [Update] banner item add

src/components/Stores/SeoOptions/index.js, src/components/Stores/SeoOptions/styles.js
Story: https://app.asana.com/0/1200268243113852/1203867986521833
=> [Update]: seo option

src/components/MyProducts/AdvancedSettings/index.js
Story: https://app.asana.com/0/home/1200268243109536/1203957978185629
=> [Update]: advanced personalization

src/components/Stores/BusinessesListing/index.js
Story: https://app.asana.com/0/1200268243113852/1203976857717714
=> [Update]: empty business

src/components/Stores/BusinessFrontLayout/index.js, src/components/Stores/BusinessFrontLayout/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203393000883249
=> Custom business layout

src/components/Stores/BusinessSalesFacebook/FacebookProfile.js, src/components/Stores/BusinessSalesFacebook/index.js, src/components/Stores/BusinessSalesGoogle/index.js, src/components/Stores/BusinessSalesInstagram/AdvancedInstagram.js, src/components/Stores/BusinessSalesInstagram/GeneralInstagram.js
Story: https://app.asana.com/0/1200268243113852/1203986121594062
=> [Upate]: social channels update

src/components/Stores/BusinessProductAddForm/index.js, src/components/Stores/BusinessServiceProfessionals/index.js, src/components/Users/OccupationSelector/index.js
STORY: https://app.asana.com/0/1198717964402573/1203962405041667
=> [Fix] Appointment issues

src/components/Stores/PaymentOption/index.js, src/components/Stores/PaymentOptionMethods/index.js, src/components/Stores/PaymentOptionPaypal/index.js, src/components/Stores/PaymentOptionStripeDirect/index.js, src/components/Stores/PaymethodOptionStripeConnect/index.js, src/components/Stores/PaymethodOptionStripeRedirect/index.js
Story: https://app.asana.com/0/1200268243113852/1203968134628554
=> [Update]: payment fix

src/components/Settings/NotificationSetting/index.js
STORY: https://app.asana.com/0/1198717964402573/1203709293313966
=> [Add] OneSignal new options for the dashbaord and web

src/components/Orders/OrdersFilterGroup/index.js, src/components/Users/CustomersListing/index.js, src/components/Users/UserFilterGroup/index.js, src/components/Users/UsersListing/index.js, src/components/Users/UsersListingHeader/index.js
Story: https://app.asana.com/0/1200268243113852/1203985818534434
=> [Update]: filter on users and orders

src/components/Marketing/BannerImageDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1203988640928622
=> [Fix] business filter for ad banner

src/components/Orders/OrdersContentHeader/index.js, src/components/Orders/OrdersFilterGroup/index.js
Story: https://app.asana.com/0/1200268243113852/1203976998832718
=> [Update]: Filter by metafield

src/components/BusinessIntelligence/InvoiceOrdertype/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204016655684057
=> [Fix] Order types UI issue

src/components/Orders/OrdersContentHeader/index.js, src/components/Orders/OrdersFilterGroup/index.js, src/components/Orders/OrdersFilterGroup/styles.js
Story: https://app.asana.com/0/1200268243113852/1203976998832718
=> [Update]: filter by multiple metafield

src/components/MyProducts/AdvancedSettings/index.js
Story: https://app.asana.com/0/1200268243113852/1203957978185619
=> [Update]: near business bad format

src/components/Settings/LanguageTransSpread/index.js, src/components/Settings/LanguageTransTable/index.js
Story: https://app.asana.com/0/1200268243113852/1203986178543385
=> [Update]: language issue

src/components/MyProducts/AdvancedSettings/index.js
Story: https://app.asana.com/0/1200268243113852/1204058937915862
=> [Update]: checkout map

src/components/Stores/BusinessAdd/BusinessDetails/index.js, src/components/Stores/BusinessAdd/BusinessDetails/styles.js, src/components/Stores/BusinessAdd/DeliveryZone/index.js, src/components/Stores/BusinessAdd/DeliveryZone/styles.js, src/components/Stores/BusinessAdd/PaymentMethods/index.js, src/components/Stores/BusinessAdd/PaymentMethods/styles.js, src/components/Stores/BusinessAdd/ReceiveOrders/index.js, src/components/Stores/BusinessAdd/ReceiveOrders/styles.js, src/components/Stores/BusinessAdd/index.js, src/components/Stores/BusinessAdd/styles.js, src/components/Stores/BusinessAddStore/index.js, src/components/Stores/BusinessProductsListing/index.js
Story: https://app.asana.com/0/1200268243113852/1203237025909906
=> [Update]: Improve create business

src/components/Messages/MessagesListing/index.js
Story: https://app.asana.com/0/1200268243113852/1204057267044829
=> [Update]: filter on message section

package.json, src/components/Loyalty/PointsWalletBusinessList/index.js, src/components/OrderingProducts/OrderingProductDetails/index.js, src/components/OrderingProducts/OrderingProductsListing/index.js, src/components/Users/CustomerCashWallet/index.js, src/components/Users/CustomerDetails/index.js, src/components/Users/CustomerPointsWallet/index.js, src/components/Users/CustomersListing/index.js, src/components/Users/ProfessionalDetail/index.js, src/components/Users/ProfessionalListing/index.js, src/components/Users/UserActiveStateFilter/index.js, src/components/Users/UserDetails/index.js, src/components/Users/UsersListing/index.js
STORY: https://app.asana.com/0/1198717964402573/1204107238461874
=> [Fix] Slider link feedback

src/components/MyProducts/OrderingWidgets/index.js, src/components/MyProducts/OrderingWidgets/styles.js, src/components/MyProducts/index.js, src/components/SidebarMenu/index.js, src/index.js, template/app.js, template/components/ListenPageChanges/index.js, template/helmetdata.json, template/pages/OrderingWidgets/index.js
Story: https://app.asana.com/0/1200268243113852/1204089619700654
=> [Feat]: Ordering widgets

src/components/Stores/BusinessLocation/index.js
STORY: https://app.asana.com/0/1198717964402573/1203952056046245
=> [Update] force update the google maps Api key

src/components/Orders/OrderBill/index.js
Story: https://app.asana.com/0/inbox/1200268243109536
=> [Update]: order cash amount

src/components/Orders/OrderNotification/index.js, src/components/Orders/OrdersManager/index.js
STORY: https://app.asana.com/0/1198717964402573/1204119396827433
=> [Fix] order notification for user details

src/components/Home/HomePage/index.js, src/components/SidebarMenu/index.js
Story: https://app.asana.com/0/1199511033583011/1203481444424105/f
=> [Update]: disabled my website functionality

src/components/Orders/OrderDetails/index.js
story: https://app.asana.com/0/1201894042190305/1204127400067789/f
=> [Fix] progress bar percentage

src/components/Delivery/UserAddForm/index.js, src/components/Delivery/UserAddForm/styles.js, src/components/Delivery/UsersList/index.js
STORY: https://app.asana.com/0/1198717964402573/1204135916793376
=> [Update] driver add as driver manager

src/components/Stores/BusinessDetails/index.js, src/components/Stores/BusinessSummary/index.js, src/components/Stores/SpoonityApiKey/index.js, src/components/Stores/SpoonityApiKey/styles.js
story: https://app.asana.com/0/1199511033583011/1203958790153727/f
=> [Feat] add spoonity api key from stores

src/components/Marketing/EnterprisePromotionList/index.js, src/components/Users/UserAddForm/index.js
Story: https://app.asana.com/0/1200268243113852/1204184977530498
=> [Update]: Dashboard issue

src/components/Delivery/DriversGroupsList/index.js, src/components/Delivery/DriversGroupsList/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204168663495828
=> [Add] Driver group Id

src/components/MyProducts/OrderingWidgets/index.js
Story: https://app.asana.com/0/1200268243113852/1204217900626848
=> [Update]: ordering widgets update

src/components/Users/CustomerPointsWallet/index.js, src/components/Users/CustomerPointsWallet/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204175294549494
=> [Add] points wallet add and reduce functionality

src/components/Shared/InputPhoneNumber/index.js, src/components/Users/UserFormDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1204227204179189
=> [Update]: remove zero from phonenumber

src/components/Orders/GiftCardsListing/index.js
STORY: https://app.asana.com/0/1198717964402573/1204240283710514
=> [Fix] gift card manager for redeemed

src/components/Stores/BusinessCateringDelivery/index.js, src/components/Stores/BusinessDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1204251467395892
=> [Fix] crash error in store details

src/components/Stores/PaymentOption/index.js
Story: https://app.asana.com/0/1200268243113852/1204251459081367
=> [Update]: paymethod fix

src/components/Stores/BusinessTypes/index.js
story: https://app.asana.com/0/1204253144878136/1204254006946907/f
=> [Fix] sentry issue id null

src/components/Stores/BusinessDeliveryZoneList/index.js
story: https://app.asana.com/0/1204253144878136/1204253878093577/f
=> [Fix] zone id null sentry issue

src/components/Stores/ProductTagsList/index.js
story: https://app.asana.com/0/1204253144878136/1204256440698429/f
=> [Fix] id null on add new label sentry

src/components/Orders/OrderBill/index.js
Story: https://app.asana.com/0/1200268243113852/1204156116024900
=> [Bug]: display delivery fee when delivery price is zero

src/components/Stores/BusinessAdd/DeliveryZone/index.js, src/components/Stores/BusinessDeliveryZoneInformation/index.js
Story: https://app.asana.com/0/1200268243113852/1204251467395871
=> [Update]: fix delivery distance

src/components/SidebarMenu/index.js
STORY: https://app.asana.com/0/1198717964402573/1204260260097547
=> [Update] professionals for business owner

src/components/Stores/ProductIngredient/index.js
story: https://app.asana.com/0/1204253144878136/1204256031930296/f
=> [Fix] sentry issue adding a new ingredient

src/components/Stores/UploadMenuGuide/index.js
Story: https://app.asana.com/0/1200268243113852/1204251575965760
=> [Bug]: upload menu on product list

src/components/MyProducts/AdvancedSettings/ButtonShadow.js, src/components/MyProducts/AdvancedSettings/FontStyleGroup.js, src/components/MyProducts/AdvancedSettings/HideCheckBox.js, src/components/MyProducts/AdvancedSettings/ImageBox.js, src/components/MyProducts/AdvancedSettings/SettingComponent.js, src/components/MyProducts/AdvancedSettings/index.js, src/components/MyProducts/AppResources/index.js
Story: https://app.asana.com/0/1200268243113852/1204217969736444
=> Advanced personalize

src/components/Settings/SettingsList/index.js
Reverts Ordering-Inc/Ordering-UI-Admin#847
=> Revert "[FEAT] settings not allowed"

src/components/Users/ProfessionalListing/index.js
STORY: https://app.asana.com/0/1198717964402573/1204284126712263
=> [Add] error alert

src/components/Marketing/EnterprisePromotionListing/index.js
STORY: https://app.asana.com/0/1198717964402573/1204271637215179
=> [Fix] add new promotion rules crash

src/components/Stores/SpoonityApiKey/index.js
story: https://app.asana.com/0/1199511033583011/1203958790153727/f
=> [Fix] spoonity store key were not saving state

src/components/Delivery/DriversGroupLogistics/index.js
Story: https://app.asana.com/0/1200268243113852/1204320661454551
=> [Bug]: delivery automation

src/components/Orders/Messages/index.js
STORY: https://app.asana.com/0/1198717964402573/1204300832188486
=> [Add] message basic info

src/components/Stores/BusinessAdd/DeliveryZone/index.js, src/components/Stores/BusinessDeliveryZoneInformation/index.js
Story: https://app.asana.com/0/1200268243113852/1204323046513449
=> [Bug]: business delivery zone distance

src/components/Orders/OrderBill/index.js
Story: https://app.asana.com/0/1200268243113852/1204322022432507
=> [Bug]: display order payment method

src/components/OrderingProducts/SiteTheme/index.js
stroy: https://app.asana.com/0/1204253144878136/1204254418131456/f
=> [Fix] crash reading property in theme optiongs

src/components/Home/HomePage/index.js, src/components/SidebarMenu/index.js
Story: https://app.asana.com/0/1200268243113852/1204355841649337
=> [Update]: revert changes for custom website

src/components/Login/LoginForm/index.js
Story: https://app.asana.com/0/1204261346907681/1204355999161826/f
video: https://d.pr/v/iQJMHg
=> [FEAT] fix

src/components/Stores/SeoOptions/index.js
story: https://app.asana.com/0/1204253144878136/1204264294550362/f
=> [Fix] white screen & console error detected by sentry

src/components/Orders/OrderBill/index.js
story: https://app.asana.com/0/1204253144878136/1204261535068660/f
=> [Fix] sentry issue in order bill

src/config/constants.js
STORY: https://app.asana.com/0/1198717964402573/1204365353590487
=> [Add] country code for Sint Maarten

src/components/Shared/ConfirmAdmin/index.js
STORY: https://app.asana.com/0/1198717964402573/1204414139735996
=> [Update] confirm admin default email or cellphone

src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderDetailsHeader/index.js, src/components/Orders/OrderDetailsHeader/styles.js, src/components/Orders/OrderToPrintTicket/index.js, src/components/Orders/OrderToPrintTicket/styles.js
story: https://app.asana.com/0/0/1204411608092694/f
=> [Feat] print ticket component

src/components/Orders/Messages/index.js
Story: https://app.asana.com/0/1200268243113852/1204428338409815
=> [Bug]: display previous message

package.json, src/components/Stores/BusinessDetails/index.js, src/components/Stores/BusinessQRCodeOption/index.js, src/components/Stores/BusinessQRCodeOption/styles.js, src/components/Stores/BusinessQRCodeOptions/index.js, src/components/Stores/BusinessQRCodeOptions/styles.js, src/components/Stores/BusinessSummary/index.js, src/components/Stores/index.js, src/utils/index.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202437258226249
=> [Feat]: QR code

src/components/Orders/OrderToPrintTicket/styles.js
story: https://app.asana.com/0/0/1204411608092694/f
=> [Fix] change font for printer component

src/components/MyProducts/AdvancedSettings/OrderType.js, src/components/MyProducts/AdvancedSettings/index.js
Story: https://app.asana.com/0/1200268243113852/1204392854450442
=> [Update]: advanced theme setting

src/components/Stores/BusinessDeliveryZoneInformation/index.js
Story: https://app.asana.com/0/1200268243113852/1204470481276285
=> [Bug]: allow decmals in distance based

src/components/Stores/BusinessSummary/index.js
Story: https://app.asana.com/0/1199511033583011/1204479854886994/f
=> [FEAT] hide-personalization-for-business-owner

src/components/Orders/OrderBill/RefundToWallet.js, src/components/Orders/OrderBill/index.js, src/components/Orders/OrderBill/styles.js, src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderDetailsHeader/index.js
STORY: https://app.asana.com/0/1198717964402573/1203695898591548
=> [Add] order refund

src/components/BusinessIntelligence/AnalyticsBusinessFilter/index.js, src/components/BusinessIntelligence/AnalyticsBusinessFilter/styles.js
Story: https://app.asana.com/0/1200268243113852/1204498357936088
=> [Update]: city filter on business filter

index.html, public/push/onesignal/OneSignalSDKUpdaterWorker.js, public/push/onesignal/OneSignalSDKWorker.js, template/app.js, template/config.json
STORY: https://app.asana.com/0/1198717964402573/1204497017419820
=> [Feat] OneSignal push notification

src/components/Orders/OrdersListing/index.js, src/components/Orders/OrdersTable/index.js
Story: https://app.asana.com/0/1200268243113852/1204519068768873
=> [Update]: external id on orderlist

src/components/BusinessIntelligence/AnalyticsBusinessFilter/index.js, src/components/BusinessIntelligence/AnalyticsBusinessFilter/styles.js
Story: https://app.asana.com/0/1200268243113852/1204498357936088
=> [Update]: country filter on business filter

src/components/Orders/OrdersTable/index.js
Story: https://app.asana.com/0/1200268243113852/1204515252368571
=> [Update]: guest user

src/components/Orders/OrderBill/RefundToWallet.js
STORY: https://app.asana.com/0/1198717964402573/1204532463403575
=> [Fix] Order refund feedback

src/components/Orders/OrderDetails/index.js, src/components/Orders/OrdersCards/index.js, src/components/Orders/OrdersTable/index.js
STORY: https://app.asana.com/0/1198717964402573/1204522296664758
=> [Update] order delivery date

src/components/Settings/DoordashConnect/index.js, src/components/Settings/LalamoveConnect/index.js, src/components/Settings/PickerExpress/index.js
Story: https://app.asana.com/0/1200268243113852/1204532883109532
=> [Update]: purchase button

src/components/MyProducts/AdvancedSettings/index.js, src/components/MyProducts/AdvancedSettings/styles.js, src/components/MyProducts/UploadAudio/index.js, src/components/MyProducts/UploadAudio/styles.js, src/components/MyProducts/index.js
Story: https://app.asana.com/0/1200268243113852/1204526767405345
=> Custom sounds

src/components/CartRecovery/RecoveryGeneral/index.js
STORY: https://app.asana.com/0/1198717964402573/1204484511123661
=> [Fix] cart recovery time setting issue

src/components/Delivery/DriversGroupDetails/index.js, src/components/Delivery/DriversGroupsListing/index.js, src/components/Delivery/DriversMarkAsBusy/index.js
STORY: https://app.asana.com/0/1198717964402573/1204532885151651
=> [Update] driver group details

src/components/Settings/DoordashConnect/index.js
Story: https://app.asana.com/0/1200268243113852/1204552119494966
=> [Update]: contact us button

src/components/Stores/BusinessQRCodeOption/index.js
Story: https://app.asana.com/0/inbox/1200268243109536
=> [Update]: QR cod feedback

src/components/Orders/OrderToPrintTicket/styles.js
story: https://app.asana.com/0/0/1204411608092694/f
=> [Update] change font color

src/components/Orders/OrderBill/index.js
STORY: https://app.asana.com/0/1198717964402573/1204555032772366
=> hide refund button for gift card orders

src/components/Orders/OrdersTable/index.js
STORY: https://app.asana.com/0/1198717964402573/1204518186361465
=> [Add] row in color setting validation

src/components/CartRecovery/RecoveryActionAdd/index.js, src/components/CartRecovery/RecoveryActionAdd/styles.js, src/components/CartRecovery/RecoveryActionListing/index.js, src/components/CartRecovery/RecoveryActionListing/styles.js, src/components/CartRecovery/RecoveryNotificationList/index.js, src/components/CartRecovery/RecoveryNotificationList/styles.js, src/components/CartRecovery/SingleRecoveryNotification/index.js, src/components/CartRecovery/index.js, src/components/Shared/HtmlEditor/InsertImage/index.js, src/components/Shared/HtmlEditor/InsertImage/styles.js, src/components/Shared/HtmlEditor/InsertLink/index.js, src/components/Shared/HtmlEditor/InsertLink/styles.js, src/components/Shared/HtmlEditor/InsertVideo/index.js, src/components/Shared/HtmlEditor/InsertVideo/styles.js, src/components/Shared/HtmlEditor/index.js, src/components/Shared/HtmlEditor/styles.js, src/components/Shared/index.js, src/index.js
STORY: https://app.asana.com/0/1198717964402573/1203715301535656
=> [Update] add cart recovery action

src/components/Orders/DeliveriesLocation/index.js
story: https://app.asana.com/0/1204253144878136/1204277925269367/f
=> [Fix] sentry issue zoom map

src/components/Delivery/DriversGroupAddForm/AdvancedLogisticsForm/index.js, src/components/Delivery/DriversGroupAddForm/AdvancedLogisticsForm/styles.js, src/components/Delivery/DriversGroupAddForm/BusinessesForm/index.js, src/components/Delivery/DriversGroupAddForm/BusinessesForm/styles.js, src/components/Delivery/DriversGroupAddForm/GeneralForm/index.js, src/components/Delivery/DriversGroupAddForm/GeneralForm/styles.js, src/components/Delivery/DriversGroupAddForm/PaymethodsForm/index.js, src/components/Delivery/DriversGroupAddForm/PaymethodsForm/styles.js, src/components/Delivery/DriversGroupAddForm/index.js, src/components/Delivery/DriversGroupAddForm/styles.js, src/components/Delivery/DriversGroupOrders/index.js, src/components/Delivery/DriversGroupsList/styles.js, src/components/Delivery/DriversGroupsListing/index.js, src/components/Delivery/DriversGroupsListing/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203715148670414
=> [Feat] New delivery automation process

src/components/Orders/OrdersTable/index.js
Story: https://app.asana.com/0/1200268243113852/1204335275236352
=> [Update]: show driver group id

src/components/Orders/CompanySelector/index.js, src/components/Orders/CompanySelector/styles.js, src/components/Orders/OrderContactInformation/index.js
story: https://app.asana.com/0/0/1203344796632293/f
=> [Feat] select companys from order details

src/components/Orders/OrderNotification/index.js
STORY: https://app.asana.com/0/1198717964402573/1204487956763059
=> Order notification

src/components/Users/CustomersListing/index.js
Story: https://app.asana.com/0/1200268243113852/1204572644341365
=> [Update]: customer filter

src/components/Delivery/DriversCompaniesList/styles.js, src/components/Delivery/DriversCompaniesListing/index.js, src/components/Delivery/DriversCompaniesListing/styles.js, src/components/Delivery/DriversCompanyAddForm/GeneralForm/index.js, src/components/Delivery/DriversCompanyAddForm/GeneralForm/styles.js, src/components/Delivery/DriversCompanyAddForm/ScheduleForm/index.js, src/components/Delivery/DriversCompanyAddForm/ScheduleForm/styles.js, src/components/Delivery/DriversCompanyAddForm/WebhooksForm/index.js, src/components/Delivery/DriversCompanyAddForm/WebhooksForm/styles.js, src/components/Delivery/DriversCompanyAddForm/index.js, src/components/Delivery/DriversCompanyAddForm/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203715204860609
=> [Add] new delivery company

src/components/Stores/BusinessDetails/index.js, src/components/Stores/BusinessSalesChannel/index.js, src/components/Stores/BusinessSalesFacebook/FacebookProfile.js, src/components/Stores/BusinessSalesFacebook/index.js, src/components/Stores/BusinessSalesGoogle/index.js, src/components/Stores/BusinessSalesInstagram/AdvancedInstagram.js, src/components/Stores/BusinessSalesInstagram/GeneralInstagram.js, src/components/Stores/BusinessSalesInstagram/index.js
Story: https://app.asana.com/0/1200268243113852/1204572644341360
=> [Update]: business sales channel

src/components/Shared/InputPhoneNumber/index.js, src/utils/index.js
STORY: https://app.asana.com/0/1198717964402573/1204590569307439
=> [Fix] crash error in user details

src/components/MyProducts/AdvancedSettings/index.js
story: https://app.asana.com/0/0/1204566686293742/f
=> [Add] order type images

src/components/CartRecovery/RecoveryActionAdd/index.js, src/components/CartRecovery/RecoveryGeneral/index.js
STORY: https://app.asana.com/0/1198717964402573/1204573384321695
=> [Add] second to cart recovery action

src/components/Orders/OrderDetails/index.js, src/utils/index.js
story: https://app.asana.com/0/1201894042190305/1204578864994280/f
=> [Add] status bar for pick up

src/components/MyProducts/OrderingWebsite/SelectBusiness.js, src/components/MyProducts/OrderingWebsite/SelectFranchise.js, src/components/MyProducts/OrderingWebsite/index.js, src/components/MyProducts/OrderingWebsite/styles.js
STORY: https://app.asana.com/0/1198717964402573/1203518580475813
=> [Update] website theme

src/components/Stores/BusinessDeviceDetail/index.js, src/components/Stores/BusinessDeviceDetail/styles.js, template/config.json
Story: https://app.asana.com/0/1200268243113852/1204582714534493
=> [Update]: kiosk and pos management

src/components/Orders/OrderToPrintTicket/index.js
Story: https://app.asana.com/0/1200268243113852/1204604630397331
=> [Update]: orderToPrintTicket

src/components/SidebarMenu/index.js
Story: https://app.asana.com/0/1200268243113852/1204613207950131
=> [Update]: remove gift card for driver manager

src/components/Stores/index.js, src/index.js
Story: https://app.asana.com/0/1199511033583011/1204589023677019/f
=> [FEAT] missing exports

src/components/Orders/Logistics/index.js, src/components/Orders/Logistics/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204583606123510
=> Advanced logistics

src/components/Orders/OrderBill/index.js
STORY: https://app.asana.com/0/1198717964402573/1204624935410544
=> hide the refund button for gift card order

src/components/Delivery/DriversGroupAddForm/GeneralForm/index.js, src/components/Delivery/DriversGroupAddForm/index.js, src/components/Delivery/DriversGroupAddForm/styles.js, src/components/Shared/SearchBar/index.js, src/components/Shared/SearchBar/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204621962645543
=> [Fix] delivery automation feedback

src/components/MyProducts/OrderingWebsite/index.js, src/components/MyProducts/OrderingWebsite/styles.js
Story: https://app.asana.com/0/inbox/1200268243109536/1204622382911688/1204623746366021
=> [Update]: custom domain

src/components/Orders/DriversList/index.js, src/components/Orders/DriversList/styles.js, src/components/Orders/OrdersListing/index.js, src/components/Orders/OrdersManager/Layouts/VeloccyOrdersManager/DriversManager/index.js, src/components/Orders/OrdersManager/Layouts/VeloccyOrdersManager/index.js, src/components/Orders/OrdersTable/index.js
STORY: https://app.asana.com/0/1198717964402573/1204604630399435
=> [Update] new layout

src/components/Messages/MessagesListing/index.js
Story: https://app.asana.com/0/1200268243113852/1204623502292432
=> [Update]: Sla filter

src/components/Orders/OrderNotification/index.js
STORY: https://app.asana.com/0/1198717964402573/1204623500557893
=> [Add] validation for order notification

src/components/CartRecovery/SingleRecoveryNotification/index.js, src/components/CartRecovery/SingleRecoveryNotification/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204621970220665
=> [Fix] Cart recovery feedback

src/components/Delivery/UserAddForm/index.js, src/components/Delivery/UserAddForm/styles.js
Story: https://app.asana.com/0/1200268243113852/1204632725678756
=> [Update]: timezone on the register of driver

src/components/MyProducts/CustomDomain/index.js, src/components/MyProducts/CustomDomain/styles.js
Story: https://app.asana.com/0/1200268243113852/1204658587993833
=> [UPdate]: custom domain feedback

src/components/Orders/OrderBill/RefundToWallet.js
STORY: https://app.asana.com/0/1198717964402573/1204653844553903
=> [Update] refund button show validation

package.json, src/components/Home/HomePage/index.js, src/components/Home/HomePage/styles.js, yarn.lock
Story: https://app.asana.com/0/1200268243113852/1204633087335607
=> [Feat]: design ordering button

src/components/Orders/WebsocketStatus/index.js, src/components/Orders/WebsocketStatus/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204678505774815
=> [Update] websocket status

src/components/Stores/BusinessQRCodeOption/index.js, src/components/Stores/BusinessQRCodeOption/styles.js
Story: https://app.asana.com/0/1200268243113852/1204679119128006
=> [Update]: QR code for eatin

src/components/BusinessIntelligence/AnalyticsCalendar/index.js, src/components/Shared/RangeCalendar/index.js, src/utils/index.js
Story: https://app.asana.com/0/1200268243113852/1204673711000255
=> [Update]: calendar language update

src/components/Login/LoginForm/index.js, template/components/AutologinParams/index.js
STORY: https://app.asana.com/0/1198717964402573/1204673711000246
=> [Fix] Default language issue

src/components/Orders/WebsocketStatus/index.js
STORY: https://app.asana.com/0/1198717964402573/1204698636303685
=> [Update] multi language content

src/components/Settings/BacCredomatic/index.js, src/components/Settings/BacCredomatic/styles.js, src/components/Settings/IntegrationListing/Analytics.js, src/components/Settings/IntegrationListing/PaymentGateway.js, src/components/Settings/IntegrationListing/index.js, src/components/Settings/index.js
Story: https://app.asana.com/0/1200268243113852/1204716519295805
=> [Update]: integrations feedback

src/components/MyProducts/AdvancedLayouts/index.js, src/components/MyProducts/OrderingWebsite/index.js, src/components/MyProducts/OrderingWebsite/styles.js
Story: https://app.asana.com/0/1200268243113852/1204687993925233
=> [Update]: settings

src/components/Stores/ImporterHelpContent/index.js, src/components/Stores/ImportersButton/index.js
Story: https://app.asana.com/0/1199511033583011/1204738146110620/f
https://app.asana.com/0/1199511033583011/1204673711000250/f
=> [FEAT] fix-importer-sidebar-and-texts

src/components/MyProducts/OrderingWebsite/index.js, src/components/Shared/ImageCrop/index.js
Story: https://app.asana.com/0/1200268243113852/1204735396231411
=> [Update]: image crop

src/components/Marketing/BannerDetails/AddBanner.js, src/components/Marketing/BannerDetails/Businesses/index.js, src/components/Marketing/BannerDetails/Businesses/styles.js, src/components/Marketing/BannerDetails/index.js, src/components/Marketing/BannerDetails/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204592094895327
=> [Update] banner for business page

src/components/Stores/BusinessQRCodeOption/index.js
Story: https://app.asana.com/0/1200268243113852/1204771596909038
=> [Update]: spell fix of table number in QR code

src/components/Stores/BusinessProductsListing/index.js
Story: https://app.asana.com/0/1200268243113852/1204763107710189
=> [Update]: improvement spreadsheet

src/components/Orders/OrderDetailsHeader/index.js, src/components/Orders/OrderDetailsHeader/styles.js
Story: https://app.asana.com/0/1204023371990854/1204796272180708/f
=> [FEAT] show-external-id

src/components/Orders/CreateCustomOrder/CartBill/index.js, src/components/Orders/CreateCustomOrder/CartBill/styles.js, src/components/Orders/CreateCustomOrder/CouponControl/index.js, src/components/Orders/CreateCustomOrder/CouponControl/styles.js, src/components/Orders/CreateCustomOrder/CustomOrderDetails/index.js, src/components/Orders/CreateCustomOrder/DriverTips/index.js, src/components/Orders/CreateCustomOrder/PaymentOptionWallet/index.js, src/components/Orders/CreateCustomOrder/PaymentOptions/index.js, src/components/Orders/CreateCustomOrder/SelectCustomer/index.js, src/components/Orders/CreateCustomOrder/SelectProducts/index.js, src/components/Orders/CreateCustomOrder/SelectProducts/styles.js, src/components/Orders/CreateCustomOrder/SingleProductCard/index.js, src/components/Orders/CreateCustomOrder/SingleProductCard/styles.js, src/components/Orders/CreateCustomOrder/TaxInformation/index.js, src/components/Orders/CreateCustomOrder/TaxInformation/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204768466871414
=> [Fix] Custom order feedback

src/components/Orders/DeliveriesManager/index.js, src/components/Orders/OrdersManager/index.js
Story: https://app.asana.com/0/1199511033583011/1204797282657296/f
=> [FEAT] fix-sla-filter-order-numbers

src/components/OrderingProducts/SiteTheme/index.js
story: https://app.asana.com/0/1204253144878136/1204393212994539/f
=> [Fix] white screen in ordering products section

src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/ProductExtraOptions/index.js, src/components/Stores/ProductExtraOptions/styles.js, src/components/Stores/ProductExtras/index.js
STORY: https://app.asana.com/0/1198717964402573/1204785506263527
=> [Update] Product options

src/components/BusinessIntelligence/AnalyticsOrdersStatus/index.js, src/components/BusinessIntelligence/BusinessAnalytics/index.js, src/components/BusinessIntelligence/CountryFilter/index.js, src/components/BusinessIntelligence/DriverAnalytics/index.js, src/components/BusinessIntelligence/ReportsBusinessDistance/index.js, src/components/BusinessIntelligence/ReportsBusinessSpend/index.js, src/components/BusinessIntelligence/ReportsDriverDistance/index.js, src/components/BusinessIntelligence/ReportsDriverOrder/index.js, src/components/BusinessIntelligence/ReportsDriverOrderTime/index.js, src/components/BusinessIntelligence/ReportsDriverSpend/index.js, src/components/BusinessIntelligence/ReportsGeneralSales/index.js, src/components/BusinessIntelligence/ReportsHeatMap/index.js, src/components/BusinessIntelligence/ReportsOrderDistance/index.js, src/components/BusinessIntelligence/ReportsOrderStatus/index.js, src/components/BusinessIntelligence/ReportsOrders/index.js, src/components/BusinessIntelligence/ReportsSaleAndCategory/index.js, src/components/BusinessIntelligence/ReportsSales/index.js
Story: https://app.asana.com/0/1200268243113852/1204785782617987
=> Country popup

src/components/Delivery/DriversGroupDetails/index.js, src/components/Delivery/DriversGroupGeneralForm/index.js, src/components/Delivery/DriversGroupGeneralForm/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204826147830392
=> [Update] always show the advanced logistics

src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/ProductExtraOptions/index.js, src/components/Stores/ProductExtraSuboption/index.js, src/components/Stores/ProductExtras/index.js, src/components/Stores/ProductSummary/index.js
Story: https://app.asana.com/0/1200268243113852/1201126801942443
=> [Update]: duplicate

src/components/Marketing/BannerDetails/Businesses/index.js
STORY: https://app.asana.com/0/1198717964402573/1204843278286004
=> [Fix] crash error

src/components/Delivery/UserAddForm/index.js, src/components/Delivery/UserFormDetails/index.js
STORY: https://app.asana.com/0/1199511033583011/1204855749066381/f
=> [Add] external id field for drivers

src/components/MyProducts/OrderingWebsite/index.js, src/components/SidebarMenu/index.js, src/components/Stores/BusinessProductsListing/index.js, src/components/Stores/BusinessQRCodeOption/index.js, src/components/Stores/BusinessSummary/index.js
Story: https://app.asana.com/0/inbox/1200268243109536/1204828006767670/1204837799614327
=> [Update]: site url feedback

src/components/Orders/OrderBill/RefundToWallet.js
STORY: https://app.asana.com/0/1198717964402573/1204760869658078
=> Improvements for Refund Wallet

src/components/Delivery/DriversGroupLogs/index.js
STORY: https://app.asana.com/0/1198717964402573/1204873696374439
=> [Fix] crash in driver logs

src/components/Orders/CreateCustomOrder/SelectCustomer/index.js, src/components/Orders/CreateCustomOrder/SelectProducts/index.js, src/components/Orders/CreateCustomOrder/SelectProducts/styles.js, src/components/Users/UserAddForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1204877440615150
=> [Update] feedback for custom order

src/components/Shared/Schedule/index.js
STROY: https://app.asana.com/0/1198717964402573/1204868592290185
=> [Fix] Schedule time format

src/components/Orders/OrderBill/RefundToWallet.js
STORY: https://app.asana.com/0/1198717964402573/1204882720182494
=> [Fix] Refund wallet feedback

src/components/Delivery/DeliveryUsersListing/index.js, src/components/Delivery/UsersList/index.js, src/components/Delivery/UsersList/styles.js, src/components/Orders/OrdersContentHeader/index.js, src/components/Orders/OrdersContentHeader/styles.js, src/components/Orders/OrdersManager/index.js, src/components/Users/UserAddForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1204920277269419
=> Fix Important

src/components/Orders/CompanySelector/index.js, src/components/Orders/CompanySelector/styles.js, src/components/Orders/DriverSelector/index.js, src/components/Orders/DriverSelector/styles.js, src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderContactInformation/styles.js, src/components/Orders/OrderDetails/styles.js, src/components/Orders/OrderStatusTypeSelector/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204911633652696
=> [Fix] drop downs style issue

src/components/Settings/GuestCheckoutFieldsSetting/index.js, src/components/Settings/GuestCheckoutFieldsSetting/styles.js, src/components/Settings/Settings/index.js, src/components/Settings/index.js
Story: https://app.asana.com/0/1200268243113852/1204729057866263
=> [Feat]: guest checkout field setting

index.html
story: https://app.asana.com/0/1204253144878136/1204839666210322/f
=> [Fix] sentry issue

src/components/Orders/DriverSelector/index.js, src/components/Orders/DriversList/index.js, src/components/Orders/DriversList/styles.js, src/components/Orders/OrderDetails/index.js
Story: https://app.asana.com/0/1199511033583011/1204928098441341/f
=> [FEAT] change

src/components/Delivery/DriversMarkAsBusy/index.js, src/components/Delivery/DriversMarkAsBusy/styles.js
Story: https://app.asana.com/0/1199511033583011/1204929069048555/f
=> [FEAT] add new busy order status

src/components/Delivery/DriversGroupAutoassign/index.js, src/components/Delivery/DriversGroupAutoassign/styles.js, src/components/Orders/OrdersContentHeader/index.js, src/components/Orders/OrdersFilterGroup/index.js, src/components/Orders/OrdersFilterGroup/styles.js, src/components/Users/UsersList/index.js, src/components/Users/UsersList/styles.js
Story: https://app.asana.com/0/1200268243113852/1204920209988056
=> [Update]: improvement

src/components/BusinessIntelligence/AnalyticsOrdersAcceptSpend/index.js, src/components/BusinessIntelligence/AnalyticsOrdersAcceptSpend/styles.js, src/components/BusinessIntelligence/AnalyticsSpendList/index.js, src/components/BusinessIntelligence/AnalyticsSpendList/styles.js, src/components/BusinessIntelligence/AnalyticsSpendTimes/index.js, src/utils/index.js
Story: https://app.asana.com/0/1200268243113852/1204921232045028
=> [Update]: report improvement

src/components/Orders/BusinessesSelector/styles.js, src/components/Orders/CountryFilter/styles.js, src/components/Orders/CreateCustomOrder/CustomOrderDetails/index.js, src/components/Orders/CreateCustomOrder/Map/index.js, src/components/Orders/CreateCustomOrder/OrderTypeSelector/index.js, src/components/Orders/CreateCustomOrder/SelectCustomer/index.js, src/components/Orders/CreateCustomOrder/SelectCustomer/styles.js, src/components/Orders/CurrencyFilter/styles.js, src/components/Orders/DateTypeSelector/styles.js, src/components/Orders/DriverMultiSelector/index.js, src/components/Orders/DriverMultiSelector/styles.js, src/components/Orders/DriversGroupTypeSelector/styles.js, src/components/Orders/OrdersFilterGroup/index.js, src/components/Orders/OrdersFilterGroup/styles.js, src/components/Shared/CitySelector/styles.js, src/components/Shared/InputPhoneNumber/index.js, src/components/Users/UserAddForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1204918958495556
=> Custom order improvements

src/components/Orders/Messages/index.js, src/components/Orders/OrdersFilterGroup/index.js
Story: https://app.asana.com/0/1200268243113852/1204937236075757
=> [Update]: local time fix

src/components/Delivery/DriversGroupLogs/index.js, src/components/Delivery/DriversGroupLogs/styles.js
Story: https://app.asana.com/0/1199511033583011/1204945380207853/f
=> [FEAT] fix texts driver logs

src/components/MyProducts/OrderingWebsite/index.js, src/components/MyProducts/OrderingWebsite/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204956643637332
=> [Add] Background Color Setting

src/components/Orders/OrdersTable/index.js
STORY: https://app.asana.com/0/inbox/1198717964396322/1204979990644177/1204937173458225
=> [Fix] visual issue

src/components/Orders/CreateCustomOrder/CustomOrderDetails/index.js, src/components/Orders/CreateCustomOrder/CustomOrderDetails/styles.js
Story: https://app.asana.com/0/inbox/1200268243109536/1204937705699251/1204938760663895
=> [Update]: order by total

src/components/Orders/OrdersContentHeader/index.js, src/components/Orders/OrdersFilterGroup/index.js
Story: https://app.asana.com/0/1200268243113852/1204974530333939
=> [Update]: unassigned filter

src/components/Delivery/AddressList/index.js, src/components/Orders/AllInOne/index.js, src/components/Orders/CreateCustomOrder/CustomOrderDetails/index.js, src/components/Orders/CreateCustomOrder/OrderTypeSelector/index.js, src/components/Orders/CreateCustomOrder/SelectCustomer/index.js, src/components/Orders/CreateCustomOrder/SelectCustomer/styles.js, src/components/Orders/DeliveriesManager/index.js, src/components/Orders/DeliveryDashboard/index.js, src/components/Orders/OrderStatusFilterBar/index.js, src/components/Orders/OrdersContentHeader/index.js, src/components/Orders/OrdersDashboardList/index.js, src/components/Orders/OrdersListing/index.js, src/components/Orders/OrdersManager/index.js, src/components/Shared/InputPhoneNumber/index.js, src/components/Users/UserAddForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1204918959253115
=> [Fix] Dashboard feedback

src/components/Orders/OrderBill/RefundToWallet.js, src/components/Orders/OrderBill/index.js
STORY: https://app.asana.com/0/1198717964402573/1204979990644123
=> [Update] Refund wallet feedback

src/components/Home/HomePage/index.js, src/components/Orders/WebsocketStatus/index.js, src/components/Stores/BusinessAdd/ReceiveOrders/index.js, src/components/Stores/BusinessSummary/index.js
STORY: https://app.asana.com/0/1198717964402573/1204965812048965
=> [Add] Link validation by White Label Module

src/components/Stores/BusinessDeviceDetail/index.js
Story: https://app.asana.com/0/1200268243113852/1204971849289751
=> [Update]: business device detail feedback

src/components/Settings/WebhookListSelector/index.js, src/components/Stores/BusinessWebhooks/index.js
story: https://app.asana.com/0/1199511033583011/1204975573885124/f
=> [Update] add new webhooks to general and store webhooks list

src/components/BusinessIntelligence/AnalyticsDriverOrders/index.js
Story: https://app.asana.com/0/1200268243113852/1204921232045035
=> [Update]: fix with driver orders total

src/components/Orders/OrdersContentHeader/index.js, src/components/Orders/OrdersContentHeader/styles.js
STORY: https://app.asana.com/0/1198717964402573/1205001395455903
=> [Add] warning message for filters applied

src/components/Home/HomePage/index.js, src/components/Orders/WebsocketStatus/index.js
STORY: https://app.asana.com/0/1198717964402573/1205011578883677
=> [Update] white label validation

src/components/Orders/OrderNotification/index.js, src/components/Orders/OrderNotification/styles.js
Story: https://app.asana.com/0/1200268243113852/1204981748572136
=> [Update]: dont show again check

src/components/Settings/GuestCheckoutFieldsSetting/index.js, src/components/Settings/GuestCheckoutFieldsSetting/styles.js
Story: https://app.asana.com/0/1200268243113852/1205000961861789
=> Update: guest checkout setting

src/components/Orders/OrderDashboardSLASetting/index.js
story: https://app.asana.com/0/0/1205011687935935/f
=> [Update] allow add negative numbers in the sla settings

src/components/Marketing/BannerDetails/Businesses/index.js
STORY: https://app.asana.com/0/1198717964402573/1204983724684633
=> [Update] select all by default

src/components/Orders/OrdersTable/index.js
Story: https://app.asana.com/0/1200268243113852/1204988784998468
=> [Update]: saving configuration in order list

src/components/Orders/OrdersListing/index.js
Story: https://app.asana.com/0/1199511033583011/1205062391141286/f
=> [FEAT] fix message section crash

src/components/Login/LoginForm/index.js
STORY: https://app.asana.com/0/1198717964402573/1205005571539483
=> [Update] don't allow white space for project name

src/components/BusinessIntelligence/AnalyticsTopOrders/index.js, src/components/BusinessIntelligence/AnalyticsTopOrders/styles.js
Story: https://app.asana.com/0/1200268243113852/1204935938928620
=> [Update]: display orders amount

src/components/Delivery/UserFormDetails/index.js
story: https://app.asana.com/0/0/1204945440937701/f
=> [Add] mono session setting check

src/components/Stores/BusinessDeviceDetail/index.js
Story: https://app.asana.com/0/1200268243113852/1205012088660573
=> [Update]: delete business dropdown

src/components/Delivery/DriversGroupAutoassign/index.js, src/components/Delivery/DriversGroupAutoassign/styles.js
STORY: https://app.asana.com/0/1198717964402573/1205044172415332
=> [Add] new settings for auto assign

src/components/Stores/ProductIngredient/index.js
Story: https://app.asana.com/0/1200268243113852/1205059901157136
=> [Update]: fix ingredient

src/components/BusinessIntelligence/AnalyticsCalendar/index.js, src/components/BusinessIntelligence/ReportsDriverSchedule/index.js, src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderDetailsHeader/styles.js
Story: https://app.asana.com/0/1200268243113852/1205043770103860
=> [Update]: improvement and fix

src/components/Orders/OrderDetails/index.js
story: https://app.asana.com/0/1199511033583011/1204958960945031/f
=> [Update] add local time to order details in order manager

src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderDetails/styles.js
story: https://app.asana.com/0/1199511033583011/1204958960945031/f
=> [Add] business time in order details

src/components/Orders/OrdersContentHeader/index.js
story: https://app.asana.com/0/1199511033583011/1205055751054821/f
=> [Update] change default lang key

src/components/Orders/OrderDetails/index.js
story; https://app.asana.com/0/1199511033583011/1204958960945031/f
=> [Update] set utc to local

src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderDetails/styles.js
Story: https://app.asana.com/0/1200268243113852/1204981637490249
=> [Update]: add assignment comment

src/components/Delivery/UserDetails/index.js, src/components/Delivery/UserDetailsMenu/index.js, src/components/Shared/PushTokens/index.js, src/components/Shared/PushTokens/styles.js, src/components/Shared/index.js, src/components/Users/UserDetails/index.js, src/components/Users/UserDetailsMenu/index.js, template/pages/CustomersList/index.js, template/pages/ManagersList/index.js
STORY: https://app.asana.com/0/1198717964402573/1205055751054711
=> [Add] Notification token

src/components/Stores/BusinessAdd/OrderTypePriceLevel/index.js, src/components/Stores/BusinessAdd/PaymentMethods/index.js
story: https://app.asana.com/0/1199511033583011/1205087665448295/f
=> [Fix] lang keys for currency and paymethods when create new store

src/components/Stores/BusinessAdd/BusinessDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1205067238208608
=> [Update]: fix time zone

src/components/Settings/WebhookList/styles.js, src/components/Settings/WebhookListSelector/index.js, src/components/Stores/BusinessWebhooks/index.js
STORY: https://app.asana.com/0/1198717964402573/1205088983434781
=> [Add] new hook option for orders_unassigned_driver

src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1205114451152564
=> [Update]: order edit feedback

src/components/Orders/OrderDashboardSLASetting/index.js
story: https://app.asana.com/0/1199511033583011/1204988784998462/f
=> [Fix] regex for negative number

src/components/MyProducts/AdvancedSettings/index.js
story: https://app.asana.com/0/1199511033583011/1205055751054925/f
=> [Update] advance settings header from business view

src/components/Stores/BusinessInformation/index.js, src/components/Stores/BusinessInformation/styles.js
story: https://app.asana.com/0/1199511033583011/1205087665448295/f
=> [Update] currency symbols

src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1204988784998472
=> [Update]: driver assignment comment feedback

src/components/CartRecovery/OpenCartList/index.js, src/components/CartRecovery/OpenCartListing/index.js, src/components/CartRecovery/OpenCartsDetail/index.js, src/components/CartRecovery/OpenCartsDetail/styles.js
STORY: https://app.asana.com/0/1198717964402573/1204891491157580
=> [Add] cart delete functionality

src/components/BusinessIntelligence/AnalyticsOrdersOrSales/index.js
Story: https://app.asana.com/0/home/1200268243109536/1205096019465503
=> [Update]: report in analytics

src/components/Orders/OrdersFilterGroup/styles.js
STORY: https://app.asana.com/0/1198717964402573/1205094505057795
=> [Fix] filter notification bar style override issue

src/components/Stores/ProductExtras/index.js, src/components/Stores/ProductExtras/styles.js
Story: https://app.asana.com/0/1200268243113852/1205119812330067
=> [Update]: edit option name

src/components/Stores/BusinessWebhooks/index.js
story: https://app.asana.com/0/1199511033583011/1205088983434777/f
=> [Feat] preparation time option added to store webhooks

src/components/Orders/OrdersDashboardControls/index.js, src/components/Orders/OrdersManager/index.js
Story: https://app.asana.com/0/1200268243113852/1205138816950513
=> [Update]: csv export feedback

src/components/Orders/DriverSelector/index.js, src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderDetails/index.js
Story: https://app.asana.com/0/1200268243113852/1205184392442258
=> [Update]: manual assignment feedback

src/components/Users/CustomerDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1205137941295035
=> [Fix] slider issue

src/components/BusinessIntelligence/Reports/ReportsSlaOrders/index.js, src/components/BusinessIntelligence/Reports/ReportsSlaOrders/styles.js, src/components/BusinessIntelligence/Reports/index.js
STORY: https://app.asana.com/0/1198717964402573/1205114744932122
=> [Add] SLA orders reports

src/components/Stores/BusinessProductList/index.js
Story: https://app.asana.com/0/1200268243113852/1205187826045826
=> Product feedback

src/components/Orders/OrderContactInformation/index.js
Story: https://app.asana.com/0/1200268243113852/1205187658550919
=> Update: edit notes

src/components/Delivery/UserFormDetails/index.js
STORY: https://app.asana.com/0/1198717964402573/1205213287137694
=> [Add] do not allow white space

src/components/Stores/BusinessPaymentMethods/index.js, src/components/Stores/PaymentOption/index.js, src/components/Stores/PaymentOption/styles.js, src/components/Stores/PaymentOptionSquare/index.js, src/components/Stores/PaymentOptionSquare/styles.js
Story: https://app.asana.com/0/1200268243113852/1204451811414108
=> [Update]: Device paymethod

src/components/Orders/Messages/index.js, src/components/Orders/OrderDetailsHeader/index.js, src/components/Orders/OrdersCards/index.js, src/components/Orders/OrdersTable/index.js
story: https://app.asana.com/0/1199511033583011/1205220812648142/f
=> [Feat] setting for show external id instead of order id

src/components/Delivery/UserDetails/index.js, src/components/Delivery/UserDetailsMenu/index.js
stroy: https://app.asana.com/0/1199511033583011/1205235172893862/f
=> [Feat] settign for allow/disallow manager to edit schedule

src/components/BusinessIntelligence/DriverAnalytics/index.js
Story: https://app.asana.com/0/1200268243113852/1205094505057786
=> [Update]: Change the title of reports in driver analytics

src/components/Stores/ImporterForm/index.js
story: https://app.asana.com/0/1199511033583011/1202786348070082/f
=> [Update] show fields in advance options

src/components/Orders/OrderContactInformation/index.js
STORY: https://app.asana.com/0/1198717964402573/1205181854995401
=> [Add] External driver info

src/components/Home/HomePage/index.js
STORY: https://app.asana.com/0/1198717964402573/1205195578411811
=> White label module

src/components/Delivery/DriversGroupLogs/index.js, src/components/Delivery/DriversGroupLogs/styles.js
story: https://app.asana.com/0/1199511033583011/1205212269108243/f
=> [Feat] show schedule changes from log in modal

src/components/Stores/ChildMapplingList/index.js, src/components/Stores/ImporterForm/index.js
story: https://app.asana.com/0/1199511033583011/1202786348070082/f
=> [Fix] white spaces in the importer

src/components/BusinessIntelligence/AnalyticsAvailableTimes/index.js, src/components/BusinessIntelligence/AnalyticsBusyTimes/index.js, src/components/BusinessIntelligence/AnalyticsCustomerSatisfaction/index.js, src/components/BusinessIntelligence/AnalyticsDriverOrders/index.js, src/components/BusinessIntelligence/AnalyticsOrdersAcceptSpend/index.js, src/components/BusinessIntelligence/AnalyticsOrdersOrSales/index.js, src/components/BusinessIntelligence/AnalyticsOrdersStatus/index.js, src/components/BusinessIntelligence/AnalyticsProductCategories/index.js, src/components/BusinessIntelligence/AnalyticsRegisterUsers/index.js, src/components/BusinessIntelligence/AnalyticsSpendList/index.js, src/components/BusinessIntelligence/AnalyticsSpendTimes/index.js, src/components/BusinessIntelligence/AnalyticsTopOrders/index.js, src/components/BusinessIntelligence/GraphLoadingMessage/index.js, src/components/BusinessIntelligence/GraphLoadingMessage/styles.js
Story: https://app.asana.com/0/1200268243113852/1205207440507122
=> [Update]: analytics feedback

src/components/Orders/CreateCustomOrder/index.js
STORY: https://app.asana.com/0/1198717964402573/1205243116384722
=> [Update] Show Custom Order Button for only admin users

src/components/Orders/InterActOrderMarker/index.js
STORY: https://app.asana.com/0/1198717964402573/1205258041303606
=> [Fix] last location time

src/components/Delivery/DriversGroupLogs/index.js, src/components/Delivery/DriversGroupLogs/styles.js
story: https://app.asana.com/0/1199511033583011/1205212269108243/f
=> [Fix] hide old when null

src/components/Delivery/UserDetails/index.js, src/components/Delivery/UserDetailsMenu/index.js, src/components/Shared/Schedule/index.js, src/components/Shared/Schedule/styles.js
story: https://app.asana.com/0/1199511033583011/1205235172893862/f
=> [Update] update and fixes for allow manager edit drivers schedule

src/components/Orders/AllInOne/DriversManager/index.js, src/components/Orders/AllInOne/index.js, src/components/Orders/DriversLocation/index.js
STORY: https://app.asana.com/0/1198717964402573/1204921712312386
=> [Update] All in one

src/components/Stores/ProductDetailsAdvanced/index.js
STORY: https://app.asana.com/0/1198717964402573/1205206285742147
=> [Fix] order limit bug

src/components/Marketing/CampaignDetail/index.js, src/components/Marketing/CampaignEmail/index.js, src/components/Marketing/CampaignEmail/styles.js, src/components/Marketing/CampaignNotification/index.js, src/components/Marketing/CampaignNotification/styles.js, src/components/Marketing/CampaignSMS/index.js, src/components/Marketing/CampaignSMS/styles.js
Story: https://app.asana.com/0/1200268243113852/1205279292391079
=> [Update]: support button

src/components/BusinessIntelligence/AnalyticsBusyTimes/index.js
https://app.asana.com/0/1200268243113852/1205295230342019
=> [Update]: busy time feedback

src/components/Orders/OrderDetails/index.js, src/themes/origin/src/components/OrderDetails/index.js
https://app.asana.com/0/1200268243113852/1204846293842826
=> Update: sentry fix

src/components/Shared/Schedule/index.js, src/components/Shared/Schedule/styles.js
story: https://app.asana.com/0/1199511033583011/1205310321975726/f
=> [Fix] schedule bug when addind new lapse

src/components/Shared/Schedule/index.js
story: https://app.asana.com/0/1199511033583011/1205310321975726/f
=> [Fix] dashboard crash

src/components/Orders/OrderStatusTypeSelector/index.js
story: https://app.asana.com/0/1201894042190305/1205181779074820/f
=> [Fix] show and filter status 24 and 25

src/components/Orders/CreateCustomOrder/PaymentOptions/index.js
story: https://app.asana.com/0/1199511033583011/1205337046925351/f
=> [Fix] filter paymethods for custom orders

src/components/Orders/CreateCustomOrder/CustomOrderDetails/index.js
story: https://app.asana.com/0/1199511033583011/1205346782010776/f
=> [Fix] can assign driver to custom order

src/components/Stores/SpoonityApiKey/index.js
story: https://app.asana.com/0/1199511033583011/1205417551685831/f
=> [Fix] refresh spoonity api key when change store

src/components/Orders/OrdersDashboardList/index.js, src/components/Orders/OrdersManager/index.js, template/pages/OrdersList/index.js
Story: https://app.asana.com/0/1199511033583011/1205418496221964/f
Video: https://d.pr/v/yLVGVH
=> [FEAT] disable-socket-room-driver-and-total-amount

src/components/Orders/OrdersDashboardList/index.js, src/components/Orders/OrdersListing/index.js, src/components/Orders/OrdersTable/index.js
[FEAT] use-memoized-callback-order-list
=> [FEAT] use-memoized-callback-order-list

src/components/Orders/OrderStatusFilterBar/index.js, src/components/Orders/OrdersContentHeader/index.js, src/components/Orders/OrdersDashboard/index.js, src/components/Orders/OrdersDashboardList/index.js, src/components/Orders/OrdersListing/index.js, src/components/Orders/OrdersManager/index.js, src/components/Orders/OrdersTable/index.js
Story: https://app.asana.com/0/0/1205420236385126/f
Video: https://d.pr/v/no0d4B
=> [FEAT] setting-optimize-order-data

src/components/Orders/DeliveriesManager/index.js, src/components/Orders/DeliveryDashboard/index.js
Story: https://app.asana.com/0/0/1205420236385126/f
=> [FEAT] setting-optimize-order-data delivery dash

src/components/Orders/OrderNotification/index.js
story: https://app.asana.com/0/1199511033583011/1205428591018603/f
=> [Update] change new order notification position

src/components/Orders/OrderNotification/index.js
Story: https://app.asana.com/0/1199511033583011/1205484548066105/f
=> [FEAT] add config enable notification and style

src/components/Home/HomePage/index.js
story: https://app.asana.com/0/1199511033583011/1205478249733795/f
=> [Update] remore what do you want to see in ordering button

src/components/Login/QueryLogin/index.js, template/app.js, template/components/AutologinParams/index.js
story: https://app.asana.com/0/1199511033583011/1205444608703334/f
=> Remove loader text

src/components/MyProducts/AppLayout/index.js, src/components/MyProducts/CallCenterApp/index.js, src/components/MyProducts/CustomProject/index.js, src/components/MyProducts/CustomerApp/index.js, src/components/MyProducts/DriverApp/index.js, src/components/MyProducts/KioskApp/index.js, src/components/MyProducts/StoreApp/index.js
Story: https://app.asana.com/0/1198717964402573/1205336313031052/f
=> Link purchase now buttons

src/components/BusinessIntelligence/ReportsSpentTime/index.js, src/components/BusinessIntelligence/ReportsSpentTime/styles.js, src/components/Settings/LalaMoveConnect/index.js, src/components/Settings/LalaMoveConnect/styles.js
Hotfix for the error introduced by: https://github.com/Ordering-Inc/Ordering-UI-Admin/pull/1145/files
=> [FIX] Add removed files back

src/components/Settings/NotificationSetting/index.js
Story: https://app.asana.com/0/0/1205523729677137/f
=> [FEAT] show new settings

src/components/Orders/OrderContactInformation/styles.js, src/components/Orders/ProductItemAccordion/styles.js
Story: https://app.asana.com/0/1204975573885133/1205336313031052/f
=> [FIX] Display correctly long names

src/components/Orders/OrderContactInformation/index.js, src/components/Stores/BusinessTaxAndFees/index.js
Story: https://app.asana.com/0/1205433118337635/1205468142650775/f
=> [FEAT] isDisableDriverCompanies

src/components/Orders/DeliveriesLocation/index.js, src/components/Stores/BusinessTaxAndFees/index.js
Story: https://app.asana.com/0/1199511033583011/1205539662126712/f
=> [FEAT] delivery dashboard improvements

src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderContactInformation/styles.js
Story: https://app.asana.com/0/0/1205366264002347/f
=> [FIX] Correct contact layout

src/components/Orders/DriversGroupTypeSelector/index.js, src/components/Orders/OrdersDashboard/index.js, src/components/Orders/OrdersDashboardList/index.js, src/components/Orders/OrdersFilterGroup/index.js
story: https://app.asana.com/0/0/1205531806034306/f
=> [Feat] driver group general filter

src/components/Orders/DeliveriesLocation/index.js
Story: https://app.asana.com/0/1199511033583011/1205539662126712/f
=> [FEAT] improvement-delivery-dashboard

src/components/Orders/DeliveriesLocation/index.js
Story: https://app.asana.com/0/1199511033583011/1205539662126712/f
=> [FEAT] improvement-delivery-dashboard 1

src/components/Orders/OrdersContentHeader/index.js
Story: https://app.asana.com/0/0/1205530855711066/f
=> [FEAT] add-config-search-box-enabled

src/components/Orders/DriverSelector/index.js, src/components/Orders/OrderContactInformation/index.js
Story: https://app.asana.com/0/1205563083891731/1205578267897104/f
=> [FEAT] fix-socket-issues-order-details

src/components/Orders/AllInOne/index.js, src/components/Orders/OrdersLateralBar/index.js
Story: https://app.asana.com/0/1205563083891731/1205578267897104/f
=> [FEAT] fix-socket-issues-orders

src/components/Orders/DeliveriesManager/index.js, src/components/Orders/OrdersCards/index.js, src/components/Orders/OrdersListing/index.js, src/components/Orders/OrdersManager/index.js, src/components/Orders/OrdersManager/test.js, src/components/Orders/OrdersTable/Order.js, src/components/Orders/OrdersTable/index.js, template/config.json, template/pages/DeliveriesManager/index.js, template/pages/OrdersList/index.js
Story: https://app.asana.com/0/1205563083891731/1205539662126828/f
=> [FEAT] improvement-use-franchise-images

src/components/Orders/OrdersContentHeader/index.js
story: https://app.asana.com/0/1199511033583011/1205636639580716/f
=> [Fix] show filter button when hide search box is on

src/components/BusinessIntelligence/Reports/ReportsSlaOrders/index.js, src/components/BusinessIntelligence/Reports/ReportsSlaOrders/styles.js
story: https://app.asana.com/0/0/1205593208770952/f
=> [Add] add filters to sla reports

src/components/Stores/BusinessTaxAndFees/index.js
Story: https://app.asana.com/0/0/1205646660407818/f
=> [FEAT] business delivery tax

src/components/Orders/OrderDetails/styles.js
story: https://app.asana.com/0/1199511033583011/1205552213796785/f
=> [Fix] responsive issue in order type selector

src/components/MyProducts/AdvancedSettings/index.js
story: https://app.asana.com/0/1199511033583011/1205634092615040/f
=> [Add] add settings for reviews in my products section

src/components/Messages/MessagesListing/index.js
story: https://app.asana.com/0/1199511033583011/1205690993802097/f
=> [Fix] white screen in messages

src/components/Delivery/AddressForm/index.js, src/components/Orders/OrderContactInformation/index.js, src/components/Stores/BusinessLocation/index.js
Story: https://app.asana.com/0/0/1205733069203013/f
Video: https://d.pr/v/kTRtOh
=> [FIX] value of google address autocomplete

src/components/Orders/AllInOne/DriversManager/index.js, src/components/Orders/AllInOne/index.js, src/components/Orders/DriversBusyStatusFilter/index.js, src/components/Orders/DriversBusyStatusFilter/styles.js, src/components/Orders/DriversList/Driver.js, src/components/Orders/DriversList/index.js, src/components/Orders/DriversList/styles.js, src/components/Orders/DriversLocation/index.js, src/components/Orders/DriversOnlineOfflineFilter/index.js, src/components/Orders/DriversOnlineOfflineFilter/styles.js, src/components/Orders/OrdersListing/index.js, src/components/Orders/OrdersListing/styles.js
Story: https://app.asana.com/0/1205433118337635/1205406872045396/f
Video: https://d.pr/v/5jTlTb
=> [FEAT] all-in-one-improvements

src/components/Orders/AllInOne/DriversManager/index.js, src/components/Orders/AllInOne/index.js
Story: https://app.asana.com/0/0/1205750845615751/f
=> [FEAT] all-in-one-feedback-improvement

src/components/Stores/BusinessAdd/BusinessDetails/index.js
Story: https://app.asana.com/0/1199511033583011/1205700927638635/f
=> [FEAT] fix add business slug

src/components/BusinessIntelligence/InvoiceDriverPdf/index.js
story: https://app.asana.com/0/1199511033583011/1205723866912033/f
=> [Fix] add orders paid with wallets in driver invoices

src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderContactInformation/styles.js, src/components/Orders/OrderDetails/index.js
Story: https://app.asana.com/0/0/1205795891681010/f
=> [FEAT] fix-update-user-&-show-map

src/components/Orders/DeliveriesLocation/index.js
Story: https://app.asana.com/0/1199511033583011/1205578267897151/f
=> [FEAT] improvement-avoid-unnecesary-renders

src/components/Orders/OrderDetailsHeader/styles.js
Story: https://app.asana.com/0/1199511033583011/1205821706068325/f
=> [FEAT] fix styles order details

src/components/Orders/ProductItemAccordion/styles.js
Story: https://app.asana.com/0/1199511033583011/1205821706068325/f
=> [FEAT] fix-product-comments-style

src/components/Orders/OrdersTable/Order.js, src/components/Orders/OrdersTable/index.js, src/components/Orders/OrdersTable/styles.js
Story: https://app.asana.com/0/0/1205806633088965/f
=> [FEAT] add agent column

src/components/Stores/ProductExtras/index.js
Story: https://app.asana.com/0/1205433118337635/1205865654498023/f
=> [FEAT] fix crash product extras

src/components/Orders/OrderDetailsHeader/index.js
story: https://app.asana.com/0/1199511033583011/1205929150486795/f
=> [Fix] hide external id and show order number

src/components/Orders/OrderBill/index.js
story: https://app.asana.com/0/1199511033583011/1205929150486792/f
=> [Fix] hide delivery fee in pickup orders

src/components/Delivery/DeliveryUsersListing/index.js, src/components/Delivery/UsersList/index.js
story: https://app.asana.com/0/1199511033583011/1205713640269473/f
=> [Feat] able to mark as not busy

src/components/Orders/OrdersTable/Order.js, src/components/Orders/OrdersTable/index.js
=> Channel Added

src/components/SidebarMenu/index.js
=> Marketing & Loyalty Suite

src/components/Users/CustomersListing/index.js, src/components/Users/UsersExportCSV/index.js
=> Added user csv filter Value

src/components/Delivery/UserAddForm/index.js
Remove front end email validation
=> Remove front end email validation

src/components/Orders/CreateCustomOrder/SelectProducts/index.js
Story: https://app.asana.com/0/1199511033583011/1206073147860570/f
=> [FEAT] search product by filter

src/components/Orders/OrdersDashboardControls/index.js, src/components/Orders/OrdersManager/index.js, template/config.json, template/pages/DeliveriesManager/index.js, template/pages/OrdersList/index.js
Story: https://app.asana.com/0/1199511033583011/1206155034056598/f
=> [FEAT] add-filter-by-franchise

index-template.js, src/components/Orders/OrdersFilterGroup/index.js, src/components/Orders/OrdersHeaderFilterGroup/index.js, src/contexts/FilterValuesContext/index.js, src/index.js
=> [FEAT] filter-value-context

src/components/Orders/OrdersFilterGroup/index.js
Story: https://app.asana.com/0/0/1206264725091385/f
=> [FEAT] reorder filter options

src/components/Delivery/DriversGroupGeneralForm/index.js
Story: https://app.asana.com/0/1199511033583011/1206311880344011/f
Video: https://d.pr/v/wq88QI
=> [FEAT] fix-crash-delivery-automation

src/components/Stores/BusinessInformation/index.js, src/components/Stores/BusinessInformation/styles.js, src/utils/index.js
Story: https://app.asana.com/0/0/1206315028118838/f
Video: https://d.pr/v/LmBK9l
=> [FEAT] add-option-selector-disable-reason

src/components/Stores/BusinessInformation/index.js
Story: https://app.asana.com/0/0/1206329588326324/f
=> [FEAT] add missed option

src/components/Orders/OrdersCards/index.js, src/components/Orders/OrdersCards/styles.js, src/components/Orders/OrdersHeaderFilterGroup/index.js, src/components/Orders/OrdersHeaderFilterGroup/styles.js
Story: https://app.asana.com/0/0/1206329588326331/f
Video: https://d.pr/v/9RV7kY
=> [FEAT] fix filter header design

src/components/Stores/BusinessMenu/index.js
Story: https://app.asana.com/0/1199511033583011/1206328575863409/f
Video: https://d.pr/v/rYtSw4
=> [FEAT] add-menu-loading-skeleton

src/components/Orders/OrdersCards/styles.js, src/components/Orders/OrdersHeaderFilterGroup/styles.js
Story: https://app.asana.com/0/0/1206353125096419/f
=> [FEAT] fix design filter

src/components/Orders/OrdersContentHeader/styles.js, src/components/Orders/OrdersHeaderFilterGroup/index.js, src/components/Orders/OrdersHeaderFilterGroup/styles.js, src/components/Orders/OrdersManager/index.js, src/components/Orders/WebsocketStatus/index.js, src/components/Users/CustomersListing/index.js, src/components/Users/UserFilterGroup/index.js, src/components/Users/UsersListingHeader/index.js
Story: https://app.asana.com/0/1199511033583011/1206351585168322/f
=> [FEAT] improve-loading-filter-customers

src/components/Users/UserFilterGroup/index.js
Story: https://app.asana.com/0/1199511033583011/1206351585168322/f
=> [FEAT] add-external-user-id-filter

src/components/Orders/AdminsSelector/index.js, src/components/Orders/OrdersFilterGroup/index.js
Story: https://app.asana.com/0/1199511033583011/1206377782408493/f
=> [FEAT] fix crash

src/components/Orders/OrdersDashboardList/index.js, src/components/Orders/OrdersHeaderFilterGroup/index.js, src/components/Orders/OrdersManager/index.js
Story: https://app.asana.com/0/0/1206401433217770/f
=> [FEAT] driver group filter functionality

src/components/Orders/AllInOne/index.js, src/components/Orders/DeliveriesManager/index.js, src/components/Orders/DeliveryDashboard/index.js
Story: https://app.asana.com/0/0/1206401433217770/f
=> [FEAT] fix-filter-driver-group-for-delivery-dashboard

src/components/Stores/ProductExtraOptions/index.js, src/components/Stores/ProductExtraSuboption/index.js, src/components/Stores/ProductExtras/index.js
Story: https://app.asana.com/0/1199511033583011/1206405735266092/f
Video: https://d.pr/v/GZuxuy
=> [FEAT] fix-loading-product-extras

src/components/Orders/AllInOne/index.js, src/components/Orders/DeliveryDashboard/index.js, src/components/Orders/OrderDashboardSLASetting/index.js, src/components/Orders/OrdersCards/index.js, src/components/Orders/OrdersCards/styles.js, src/components/Orders/OrdersContentHeader/index.js, src/components/Orders/OrdersContentHeader/styles.js, src/components/Orders/OrdersDashboardSLAControls/index.js, src/components/Orders/OrdersDashboardSLAControls/styles.js, src/components/Orders/OrdersHeaderFilterGroup/styles.js, src/components/Orders/OrdersManager/index.js, src/components/Orders/WebsocketStatus/index.js
Story: https://app.asana.com/0/0/1206386116597454/f
Video: https://d.pr/v/aXGUg4
=> [FEAT] change design filters

src/components/Orders/AllInOne/index.js
Story: https://app.asana.com/0/0/1206386116597453/f
Video: https://d.pr/v/Ky4kqm
=> driver-filter-all-in-one

src/components/Users/UserFormDetails/index.js, src/components/Users/UserFormDetails/styles.js
Story: https://app.asana.com/0/1199511033583011/1206333812552314/f
=> [FEAT] add-timezone-selector-users

src/components/Delivery/DriverTemporalSchedule/index.js, src/components/Delivery/DriverTemporalSchedule/styles.js, src/components/Delivery/DriversGroupDrivers/index.js, src/components/Delivery/DriversGroupDrivers/styles.js
Story: https://app.asana.com/0/1206487310134639/1206038699169905/f
=> [FEAT] add add-temporary-drivers

src/components/Stores/ServiceDetail/index.js
Story: https://app.asana.com/0/0/1206460771085889/f
=> [FEAT] missing-language-variables

src/components/Delivery/DriverTemporalSchedule/styles.js, src/components/Delivery/DriversGroupDrivers/index.js, src/components/Delivery/DriversGroupDrivers/styles.js
Story: https://app.asana.com/0/0/1206545648329909/f
=> [FEAT] feedback-temorary-driver

src/components/Delivery/DriverTemporalSchedule/index.js
Story: https://app.asana.com/0/0/1206582124401852/f
=> [FEAT] feedback-temporary-drivers

src/components/Shared/InputPhoneNumber/index.js, src/components/Users/UserFormDetails/index.js
Story: https://app.asana.com/0/0/1206587082431499/f
=> [FEAT] add-config-phone-validation

src/components/Delivery/DeliveryUsersListing/index.js, src/components/Delivery/UserDetails/index.js, src/components/Orders/OrderBill/index.js, src/components/Orders/OrderContactInformation/index.js, src/components/Orders/OrderDetails/index.js, src/components/Orders/OrderStatusTypeSelector/index.js, src/components/Orders/OrdersContentHeader/styles.js, src/components/SidebarMenu/index.js, template/app.js
Story: https://app.asana.com/0/0/1206038699169875/f
=> [FEAT] add-read-only-level-users

src/components/Users/UserAddForm/index.js
Story: https://app.asana.com/0/0/1206602773985905/f
=> [FEAT] feedback-config-phone-validation

src/components/Stores/BusinessLogs/index.js, src/components/Stores/BusinessSummary/index.js
Story: https://app.asana.com/0/0/1206635208180908/f
=> [FEAT] business-logs-only-admins

src/components/Users/UserAddForm/index.js, src/components/Users/UserFormDetails/index.js
Story: https://app.asana.com/0/1199511033583011/1206558544547040/f
=> [FEAT] improvement-avoid-spaces-cellphone

src/components/Orders/ProductItemAccordion/index.js
Story: https://app.asana.com/0/0/1206879562872735/f
=> [FEAT] fix sort product options

src/components/Login/LoginForm/index.js, src/components/Orders/OrdersContentHeader/styles.js, src/components/Orders/OrdersManager/styles.js
Story: https://app.asana.com/0/0/1206841386725155/f
=> [FEAT] language-variable-change-&-fix-overflow

src/components/Marketing/CampaignList/index.js
Story: https://app.asana.com/0/0/1206831795093480/f
=> [FEAT] fix-campaign-pages

src/components/Marketing/CampaignHeader/index.js
Story: https://app.asana.com/0/0/1206831795093475/f
=> [FEAT] add refresh button

package.json, yarn.lock
Story; https://app.asana.com/0/0/1207592433611703/f
=> [FEAT] remove sentry

src/components/Stores/ProductDesktopPreview/index.js, src/components/Stores/ProductDesktopPreview/styles.js, src/styles/Checkbox/index.js, src/styles/index.js
Story: https://app.asana.com/0/1164464536714178/1207622709997212/f
=> [FEAT] fix-preview-product

src/components/Stores/ProductDesktopPreview/index.js, src/components/Stores/ProductSummary/index.js
Story: https://app.asana.com/0/1164464536714178/1207727425135135/f
=> [FEAT] fix-product-extra-state

src/components/Shared/Modal/index.js, src/components/Shared/Modal/styles.js, src/components/Stores/BusinessDeliveryZoneDetails/index.js, src/components/Stores/BusinessDeliveryZoneDetails/styles.js, src/components/Stores/BusinessDetails/index.js, src/components/Stores/BusinessSummary/index.js, src/components/Stores/BusinessSummary/styles.js, src/components/Stores/ProductDetails/index.js, src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/ProductExtraOptionDetails/styles.js, src/components/Stores/ProductSummary/index.js, src/components/Stores/ProductSummary/styles.js, src/components/Stores/SnoozeComponent/index.js, src/components/Stores/SnoozeComponent/styles.js, src/styles/Buttons/index.js, template/pages/BusinessProductsList/index.js
Story: https://app.asana.com/0/1164464536714178/1207126872846735/f
=> [FEAT] add-snooze-business-deliveryzones-product-extra-options

src/components/Orders/DriversList/index.js
=> [FIX] possible missing change state of driver

src/components/Orders/AllInOne/index.js, src/components/Orders/OrdersDashboard/index.js, src/components/Orders/OrdersHeaderFilterGroup/styles.js, src/components/Orders/OrdersTable/index.js, src/components/Shared/Pagination/index.js
Story: https://app.asana.com/0/1164464536714178/1207933814848355/f
=> perf: Fix max-width issue and improve selector loading

src/components/Stores/BusinessMenuOptions/index.js, src/components/Stores/BusinessMenuOptions/styles.js, src/components/Stores/BusinessProductsCategoyDetails/index.js, src/components/Stores/BusinessProductsCategoyDetails/styles.js, src/components/Stores/SnoozeComponent/index.js
Story; https://app.asana.com/0/1164464536714178/1207126872846736/f
=> [FEAT] snooze-menus-product-categories

src/components/Stores/SnoozeComponent/index.js
Story: https://app.asana.com/0/1164464536714178/1207992500888097/f
=> feat: Add date selection logic and update form state in SnoozeComponent

src/components/Stores/BusinessMenuOptions/index.js, src/components/Stores/BusinessProductsCategoyDetails/index.js, src/components/Stores/SnoozeComponent/index.js, src/components/Stores/SnoozeComponent/styles.js
Story: https://app.asana.com/0/1199567559269427/1208000090011436/f
=> feat: disable snooze functionality for menu options and product categories

src/components/Stores/BusinessDeliveryZoneDetails/index.js, src/components/Stores/ProductExtraOptionDetails/index.js, src/components/Stores/SnoozeComponent/index.js
Story: 
https://app.asana.com/0/1164464536714178/1208045877360032/f
- Update BusinessDeliveryZoneDetails component to use the zoneState's zone data instead of the business data
- Remove console.log statements from ProductExtraOptionDetails component
- Comment out snooze button in ProductExtraOptionDetails component
=> feat: Update BusinessDeliveryZoneDetails and ProductExtraOptionDetails components

src/components/Stores/BusinessMenuOptions/index.js, src/components/Stores/BusinessProductsCategoyDetails/index.js, src/components/Stores/ProductExtraOptionDetails/index.js
Story: https://app.asana.com/0/1164464536714178/1208091184837962/f
=> feat: Comment out snooze button in BusinessMenuOptions, BusinessProductsCategoyDetails, and ProductExtraOptionDetails components

src/components/Stores/ProductExtraSuboption/index.js, src/components/Stores/ProductExtras/index.js, src/components/Stores/ProductExtras/styles.js, src/components/Stores/SnoozeComponent/index.js, src/components/Stores/SnoozeComponent/styles.js
Story: https://app.asana.com/0/1164464536714178/1208091184837989/f
=> feat: Add snooze functionality to ProductExtraSuboption and ProductExtras components

src/components/Stores/BusinessPaymentMethods/index.js, src/components/Stores/PaymentOptionStripeLink/index.js, src/components/Stores/PaymentOptionStripeLink/styles.js
Story: https://app.asana.com/0/1164464536714178/1208602367363143/f
=> Refactor BusinessPaymentMethods and PaymentOptionStripeLink components

src/components/Stores/BusinessMenu/index.js, src/components/Stores/BusinessMenu/styles.js
Story: https://app.asana.com/0/1164464536714178/1208629113904671/f
=> Refactor: Update current menu state management in BusinessMenu component

src/components/Delivery/UserFormDetails/index.js
Story: https://app.asana.com/0/1164464536714178/1208812060996655/f
=> Refactor: Update translation function usage in UserFormDetails component

src/components/Delivery/DriversGroupLogs/index.js, src/components/Delivery/DriversGroupLogs/styles.js
Story: https://app.asana.com/0/1164464536714178/1208768410550739/f
=> Fix: Update attribute checks and date parsing in DriversGroupLogsUI; adjust padding in DateTimeWrapper styles

src/components/Shared/Schedule/index.js, src/components/Shared/Schedule/styles.js
Story: https://app.asana.com/0/1164464536714178/1208925184597233/f
=> feat: enhance TimeScheduleItemContainer styles for better layout and responsiveness

src/styles/Select/index.js
Story: https://app.asana.com/0/1164464536714178/1209021350502209/f
=> fix: optimize Select component's memoization by including additional props in comparison

src/components/Delivery/UsersList/index.js
Story: https://app.asana.com/0/1120945085835679/1209048235021800/f
=> fix: update pagination to use dynamic page size in UsersList component

src/components/Stores/ProductDetailsAdvanced/index.js
Story: https://app.asana.com/0/1164464536714178/1208976977890971/f
=> fix: ensure weight unit is set when weight changes in ProductDetailsAdvanced component

src/components/Settings/InsertImage/index.js
Story: https://app.asana.com/0/1164464536714178/1209096510529884/f
=> feat: add alt text input for images in InsertImage component

src/components/Orders/OrdersDashboardSLAControls/index.js, src/contexts/FilterValuesContext/index.js
Story: https://app.asana.com/0/1164464536714178/1209127099331032/f
=> feat: integrate filter values context for time status in OrdersDashboardSLAControls component

src/components/Orders/OrdersListing/index.js
Story: https://app.asana.com/0/1164464536714178/1209230098814226
=> fix: disable order number column in OrdersListing component

src/components/Stores/BusinessMenuOptions/index.js
Story: https://app.asana.com/0/1164464536714178/1209353762113512
=> feat: pass setCurrentMenu prop to BusinessMenuShare component

src/components/Orders/DeliveryDashboard/index.js
Story: https://app.asana.com/0/1164464536714178/1209353762113517
=> fix: simplify order interaction map handling in DeliveryDashboard

src/components/Delivery/UserDetails/index.js, src/components/Delivery/UserDetailsMenu/index.js
Story: https://app.asana.com/0/1164464536714178/1209353762113520
=> feat: add driver group menu option for driver managers

src/components/Orders/AllInOne/index.js
Story: https://app.asana.com/0/1164464536714178/1209444665224175
=> fix: optimize order detail display with config check

src/components/BusinessIntelligence/AnalyticsMap/index.js
Story: https://app.asana.com/0/1164464536714178/1209333710289645
=> fix: improve location validation and error handling in AnalyticsMap component

src/components/Orders/AllInOne/index.js
Introduce new state variable orderForMap to manage selected order for map display Update handleOrderClick and handleBackRedirect to manage orderForMap state Modify MapView component to use orderForMap instead of detailsOrder
=> feat: Add orderForMap state to improve order detail handling

src/components/Orders/AllInOne/index.js, src/utils/index.js
Introduce usePreventDoubleClick hook to prevent rapid clicks on order details Refactor handleOpenOrderDetail to utilize the new hook for improved user experience Update imports in index.js to include the new utility function
=> feat: Implement double-click prevention for order detail handling.

src/components/Orders/AdminsSelector/index.js, src/components/Orders/BusinessesSelector/index.js, src/components/Orders/CountryFilter/index.js, src/components/Orders/CurrencyFilter/index.js, src/components/Orders/PaymethodTypeSelector/index.js, src/components/Shared/CitySelector/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210202562677432?focus=true
=> refactor: update pagination handling in multiple selectors to use previous state for total pages calculation

src/components/Delivery/DriverGroupSetting/index.js, src/components/Delivery/DriverGroupSetting/styles.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210345223592400?focus=true
=> feat: add batch selection functionality to DriverGroupSetting component

src/utils/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210603704637429?focus=true
=> refactor: update getAttributeName function to accept functions object for improved flexibility

src/components/Delivery/DriverGroupSetting/index.js, src/components/Delivery/DriverGroupSetting/styles.js
Story: https://app.asana.com/1/306583973076188/task/1210686665968374
=> refactor: improve DriverGroupSetting component with loading state and disabled functionality

src/components/Stores/BatchImageForm/index.js, src/components/Stores/BusinessProductsListing/index.js, src/components/Stores/ProductDetails/index.js, src/components/Stores/ProductDetatilsInformation/index.js, src/components/Stores/ProductMainDetails/index.js
Story: https://app.asana.com/1/306583973076188/project/1164464536714178/task/1210985688908406?focus=true
=> feat: enhance image size validation across components

src/components/Stores/ProductDetailsAdvanced/index.js, src/components/Stores/SingleBusiness/index.js, src/components/Stores/index.js, src/index.js, src/styles/Select/FirstSelect/index.js
- Imported PaymentOptionCredomatic in Stores and updated exports accordingly.
- Added ColorPicker to Shared components and updated exports.
- Enhanced ProductDetailsAdvancedUI with new state management for form changes and modal handling.
=> feat: add PaymentOptionCredomatic and ColorPicker components to exports
